#!/bin/sh

exec 2>&1

[ -r ./conf ] && . ./conf

exec 2>&1
exec setpriv --reuid _mdnsd --regid _mdnsd --clear-groups \
	--ambient-caps +net_raw --inh-caps +net_raw --bounding-set -all,+net_raw \
	--no-new-privs -- mdnsd -n ${OPTS}
