[Additional packages]
Internet:
- epiphany: Intuitive GNOME web browser
- evolution: Integrated mail, addressbook and calendaring for GNOME
- gnome-authenticator: Two-factor authentication code generator for GNOME
- gnome-online-accounts: GNOME service to access online accounts
- polari: GNOME IRC client
Music:
- deadbeef: Ultimate Music Player for GNU/Linux
- gnome-music: GNOME music playing application
- spotify: Proprietary music streaming client (nonfree|glibc)
Video:
- totem: GNOME integrated movie player based on Gstreamer
- vlc: Cross-platform multimedia player
Other:
- chrome-gnome-shell: GNOME Shell integration for Chrome
- gcr: GNOME crypto package
- ghex: Simple binary editor for GNOME
- gitg: Git repository viewer for GTK+/GNOME
- gnome-bluetooth: GNOME Bluetooth Subsystem
- gnome-passbook: A password manager for GNOME
- gparted: Gnome Partition Editor
- orca: Screen reader for individuals who are blind or visually impaired
- qalculate-gtk: Multi-purpose desktop calculator
- sushi: Quick image previewer over DBus for Nautilus
- vino: VNC server for the GNOME desktop
- yaru-plus: Elegant Canonical's Yaru-based third-party icons theme
