# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# _CAN_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set _CAN_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The _CAN_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : /builddir/rspamd-0.9.9/build/pthread_setpshared.c
# Executable    : /builddir/rspamd-0.9.9/build/CMakeFiles/cmTryCompileExec2709940551-_CAN_RUN
# Run arguments : 
#    Called from: [1]	/builddir/rspamd-0.9.9/CMakeLists.txt

set( _CAN_RUN 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

	 set( HAVE_ATOMIC_BUILTINS_EXITCODE 
		 "0"
		 CACHE STRING "Result from TRY_RUN" FORCE)

