.Dd July 24, 2016
.Dt VKPURGE 8
.Os
.Sh NAME
.Nm vkpurge
.Nd remove old kernel files/modules
.Sh SYNOPSIS
.Nm
.Cm list
.Nm
.Cm rm
.Op Ar versions\ ... | Cm all
.Sh DESCRIPTION
The
.Nm
command is used to properly remove old or unwanted kernels from Void Linux
systems, by running the appropiate removal hooks and doing the removal.
.Ss Justification
.Xr xbps-install 1
will leave old kernels in place when the kernel package gets upgraded, and
.Xr xbps-remove 1
will only be able to remove the latest kernel in a version,
for example 4.3.4_4, but it would need to leave behind 4.3.4_3.
.Sh OPTIONS
.Bl -tag -width Ds
.It Ic list
Provide a list of installed kernel versions.
.It Ic rm
Remove kernels.
Must be followed by either a version number or the literal
.Sq Ic all .
.El
.Sh EXIT STATUS
.Nm
exits with a 0 code unless the help text was printed.
Since there is no proper invocation to trigger a print of the help,
this can be summarized: if there was a proper invocation of
.Nm
then the command will exit 0.
Otherwise, the exit code is 1.
.Sh EXAMPLES
The following will list all installed kernels.
.Bd -literal -offset indent
$ vkpurge list
.Ed
.Pp
The following command will delete the kernel version 2.6.39_2 with all
kernel-specific files such as compiled modules.
.Bd -literal -offset indent
# vkpurge rm 2.6.39_2
.Ed
.Pp
The following command will delete the kernels with version 2.6.39_2 and 4.3.4_1
.Bd -literal -offset indent
# vkpurge rm 2.6.39_2 4.3.4_1
.Ed
.Sh SEE ALSO
.Xr xbps-install 1 ,
.Xr xbps-remove 1
.Sh BUGS
There is no support as of yet for all kernels, specific series like rpi-kernel
are not supported
