.Dd April 6, 2019
.Dt VKPURGE 8
.Os
.Sh NAME
.Nm vkpurge
.Nd remove old kernel files/modules
.Sh SYNOPSIS
.Nm
.Cm list
.Op Ar version
.Nm
.Cm rm all
.Nm
.Cm rm
.Ar version ...
.Sh DESCRIPTION
The
.Nm
utility lists and removes removable kernel versions left
behind by
.Xr xbps-install 1
and
.Xr xbps-remove 1 .
.Nm
runs the appropriate removal hooks and deletes the kernel,
modules and other miscellaneous files.
.Pp
.Nm
only lists or removes kernel versions that are:
.Bl -bullet -compact
.It
not currently booted.
.It
not provided by any installed xbps package.
.El
.Pp
The
.Ar version
arguments support
.Xr sh 1
pattern matching.
.Pp
The following commands are available:
.Bl -tag -width 4n
.It Ic list Op Ar version
List removable kernel versions.
Optionally list only versions matching
.Ar version .
.It Ic rm all
Remove all removable kernel versions.
.It Ic rm Ar version ...
Remove all removable kernel versions matching
.Ar version .
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
The following command lists installed kernels matching a pattern.
.Bd -literal -offset indent
$ vkpurge list '4.18.*'
.Ed
.Pp
The following command will delete the kernel versions matching the pattern and a specified version.
.Bd -literal -offset indent
# vkpurge rm '2.6.*' 4.3.4_1
.Ed
.Sh SEE ALSO
.Xr xbps-install 1 ,
.Xr xbps-remove 1
.Sh BUGS
There is no support for all kernels. Specific series, like rpi-kernel, are not
supported yet.
