resolver: lts-15.4
packages:
  - .
extra-deps:
  - ghc-lib-parser-8.10.1.20200412
  - ghc-lib-parser-ex-8.10.0.6
  - extra-1.7.1
ghc-options: {"$locals": -ddump-to-file -ddump-hi -Werror=unused-imports -Werror=unused-top-binds -Werror=orphans}
