resolver: lts-16.13
packages: [.]
extra-deps:
  - ghc-lib-parser-8.8.4.20200716
  - ghc-lib-parser-ex-8.8.5.8
ghc-options:
    "$locals": -Wunused-imports -Worphans -Wunused-top-binds -Wunused-local-binds -Wincomplete-patterns
