- TeXLive is free software see the files:

  /usr/share/licenses/texlive2013-bin/LICENSE.TL
  /usr/share/licenses/texlive2013-bin/LICENSE.CTAN

=====================================================================

  To update your TeXLive installation use only the program

  /opt/texlive/2013/<arch>/tlmgr

  where <arch> is:
    - x86_64-linux  ==> x86_64 architecture  
    - i386-linux    ==> i386 architecture

  see:    

  http://www.tug.org/texlive/doc/tlmgr.html#EXAMPLES
          
  for the details and the documentation in

  WARNING: To avoid messing up your TeXLive installation, DON'T use
  the installation scripts in /opt/texlive2013-installer.
