.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH DRAWTERM 1 "October 16, 2008"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
drawterm \- connect to Plan 9 CPU servers from other operating systems
.SH SYNOPSIS
.B drawterm
.RB [ \-d ]\|
.RB [ -a
.IR authserver ]
.RB [ -c
.IR cpuserver ]
.RB [ -e
.IR encription_hash_algs ]
.RB [ -k
.IR keyspec ]
.RB [ -s
.IR secstoreserver ]
.RB [ -u
.IR username ]
.RB [ -C
.I command args
.IR ... ]
.br
.SH DESCRIPTION
\fBdrawterm\fP is not a Plan 9 program.
It is a program that users of non-Plan 9 systems can use to establish
graphical
.BR cpu (1)
connections with Plan 9 CPU servers.  Just as a real Plan 9 terminal does, a
\fBdrawterm\fP serves its local name space as well as some devices (the
keyboard, mouse, and screen) to a remote CPU server, which mounts this name
space on
.I /mnt/term
and starts a shell.
Typically, either explicitly or via the profile, one uses the shell to start
.BR rio (1).

.PP
By default, drawterm uses the CPU server \fB$cpu\fP or \fIcpu\fP, and the
authentication server \fB$auth\fP or \fIauth\fP,


.SH OPTIONS
This program follows the syntax of the cpu(1) Plan 9 command.

A summary of options is included below.
.TP
.B \-h
Show summary of options.
.TP
.B \-a
Specifies the authentication server to use. If not present uses the
.B $auth
environment variable, if present, or tries with a host name of
.BR auth .
.TP
.B \-c
Specifies the cpu server to use. If not present uses the
.B $cpu
environment variable, if present, or tries with a host name of
.BR cpu .
.TP
.B \-u
Specifies the username to authenticate with. If not present uses the
.B $USER
environment variable, if present, or asks interactively for an username.
.TP
.B \-s
Specifies the secstore server to use.
.TP
.B \-C
Specifies a command to be executed remotely.
.TP
.BR \-e , \-k
Allow for selecting the hash algorithm and keys used, they have the same
meaning as in \fBcpu\fP(1).

.SH SOURCE
In Plan 9 distributions, \fI/sys/src/cmd/unix/drawterm\fP.

.SH DIAGNOSTICS
Drawterm prints most diagnostics in its own window.

.SH BUGS

Although at first \fBdrawterm\fP may seem like a Plan 9 terminal, in fact it
is just a way to provide a CPU server with some terminal devices.
The difference is important because one cannot run terminal-resident programs
when using \fBdrawterm\fP.
The illusion can be improved by delicate adjustments in
\fI/usr/$user/lib/profile\fP.

Should import latest /dev/draw to allow resize of window

Should copy 9term code and make console window a real 9term window instead.

Should implement /dev/label.

.SH SEE ALSO
.BR cpu (1),
.BR rio (1)
in the Plan 9 documentation

.SH AUTHOR
drawterm was written by Russ Cox <rsc@swtch.com>.
.PP
This manual page was written by Russ Cox <rsc@swtch.com>, with modifications
by Martín Ferrari <tincho@debian.org> for the Debian project.
