#!/bin/sh
#
# PROVIDE: nfsd
# REQUIRE: mountd

$_rc_subr_loaded . /etc/rc.subr

name="nfsd"
rcvar=$name
command="/usr/sbin/rpc.nfsd"
start_postcmd="nfsd_postcmd"

nfsd_postcmd()
{
	/usr/sbin/sm-notify ${smnotify_args}
}

load_rc_config $name
run_rc_command "$1"
