# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# TEST_DID_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set TEST_DID_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# TEST_DID_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set TEST_DID_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The TEST_DID_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : /builddir/kvirc-4.2.0/cmake/datetime.cpp
# Executable    : /builddir/kvirc-4.2.0/build/CMakeFiles/cmTC_f21bc-TEST_DID_RUN
# Run arguments : 
#    Called from: [1]	/builddir/kvirc-4.2.0/CMakeLists.txt

set( TEST_DID_RUN 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( TEST_DID_RUN__TRYRUN_OUTPUT 
     "0000-00-00 00:00:00 AAA"
     CACHE STRING "Output from TRY_RUN" FORCE)


# TEST_DID_RUN_DYNLABELS
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set TEST_DID_RUN_DYNLABELS to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The TEST_DID_COMPILE_DYNLABELS variable holds the build result for this TRY_RUN().
# 
# Source file   : /builddir/kvirc-4.2.0/cmake/dynlabels.cpp
# Executable    : /builddir/kvirc-4.2.0/build/CMakeFiles/cmTC_6108c-TEST_DID_RUN_DYNLABELS
# Run arguments : 
#    Called from: [1]	/builddir/kvirc-4.2.0/CMakeLists.txt

set( TEST_DID_RUN_DYNLABELS 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

