case $ACTION in
post)
	cat <<_EOF
===========================================================================
Two systemd services are provided by ${PKGNAME}-${VERSION}:

	- sshd.service (starts a single instance of sshd)
	- sshd.socket (per-connection on demand sshd)

By default we enable the on-demand per-connection daemon, which is lighter
when there are few connections.
===========================================================================
_EOF
	;;
esac
