case $ACTION in
post)
	cat <<_EOF
===========================================================================

Two systemd services are provided by ${PKGNAME}-${VERSION}:

	- sshd.service (starts a single instance of sshd)
	- sshd.socket (per-connection on demand sshd)

Feel free to start/enable your preferred solution :-)

===========================================================================
_EOF
	;;
esac
