With the 0.4 release, river no longer provides a Wayland window manager.
Instead, you need to use a separate window manager that implements river's protocol.

A forked 0.3 package providing the legacy self-contained experience is also available: river-classic

You can find packaged window managers for river by running:

xbps-query -Rp provides -s river-wm

More info: https://isaacfreund.com/blog/river-window-management/
River WM list: https://codeberg.org/river/wiki/src/branch/main/pages/wm-list.md
