# Options
complete -r -F -c startup -l append-confdir -d 'Append directories to look for job configuration files'
complete -r -F -c startup -l confdir -d 'Read job configurationo files from this directory rather than defaults'
complete -x -c startup -l default-console -d 'Default value for "console" stanza'
complete -f -c startup -l no-cgroups -d 'Do not honour cgroup stanza'
complete -f -c startup -l no-dbus -d 'Do connect to a D-Bus bus'
complete -f -c startup -l no-inherint-env -d 'Stop jobs from inheriting initial environment'
complete -r -F -c startup -l logdir -d 'Write job output log files to this directory'
complete -f -c startup -l no-log -d 'Disable logging of job output'
complete -f -c startup -l no-session -d 'Disable chroot sessions'
complete -f -c startup -l no-startup-event -d 'Do not emit initial startup event'
complete -r -F -c startup -l prepend-confdir -d 'Prepend directories to look for job configuration files'
complete -f -c startup -l session -d 'Connect to the D-Bus session bus'
complete -x -c startup -l startup-event -d 'emit a different event at startup than the default one'
complete -f -c starutp -s q -l quiet -d 'Only output errors'
complete -f -c startup -s v -l verbose -d 'Output verbose messages about job state changes and event emissions'
complete -f -c startup -l version -d 'Output version information and exit'
