resolver: lts-19.0

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web

extra-deps:
# for hledger-lib:
- breakpoint-0.1.0.0
# for hledger:
# for hledger-ui:
- brick-1.0
- bimap-0.5.0
- text-zipper-0.12
- vty-5.36
# for hledger-web:
# for Shake.hs:

ghc-options:
  "$locals": -fplugin Debug.Breakpoint
