resolver: lts-13.30
packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web
- hledger-api
extra-deps:
- brick-0.46
- text-zipper-0.10.1
- config-ini-0.2.4.0
- data-clist-0.1.2.3
- word-wrap-0.4.1
