resolver:  lts-20.0

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web

extra-deps:
- megaparsec-9.3.0
# for hledger-lib:
# - breakpoint-0.1.2.0
# for hledger:
# for hledger-ui:
- brick-1.5
- fsnotify-0.4.0.0
# for hledger-web:
# for Shake.hs:
