.TH E2CP 1 "March 2, 2005"
.\"
.SH NAME
e2cp \- copies files from/to an e2fs filesystem
.\"
.SH SYNOPSIS
.B e2cp
.RI [ options ] " files... dest"
.\"
.SH DESCRIPTION
The \fBe2cp\fP command copies files to/from an e2fs filesystem from/to the
machine's filesystem.
.\"
.SH OPTIONS
A single `-' (dash) can be used instead of a file name to indicate standard
input/output.
.TP
.B \-0
Input lines terminated by a null character.
.TP
.B \-a
Absolute directory names - create directories instead of just copying
into the destination. Only valid for copying into an ext2fs filesystem.
.TP
.B \-d \fIdest_dir\fP
Destination of files to be copied. May be in the ext2fs filesystem or
the host filesystem.
.TP
.B \-G \fIgid\fP
Set the default group to gid.
.TP
.B \-O \fIuid\fP
Set the default file owner to uid.
.TP
.B \-p
Preserve host file attributes (permissions, times, etc.) when copying
files.
.TP
.B \-P \fImode\fP
Set the file permissions (ie 755, 666).
.TP
.B \-s \fIsrc_dir\fP
The source of the files to be copied.
.TP
.B \-v
Be verbose.
.\"
.SH SEE ALSO
.BR e2tools (7),
.BR e2ln (1),
.BR e2ls (1),
.BR e2mkdir (1),
.BR e2mv (1),
.BR e2rm (1),
.BR e2tail (1).
.\"
.SH AUTHOR
The \fBe2tools\fP were written by Keith Sheffield <sheff@pobox.com>.
.PP
This manual page was written by Lucas Wall <lwall@debian.org>,
for the Debian project (but may be used by others).
