.TH E2LN 1 "March 2, 2005"
.\"
.SH NAME
e2ln \- create hard links on an ext2 filesystem
.\"
.SH SYNOPSIS
.B e2ln
.RI [ options ] " source destination"
.\"
.SH DESCRIPTION
The \fBe2ln\fP command is used to create hard links on an ext2 filesystem.
.\"
.SH OPTIONS
.TP
.B \-f
Force the operation to remove any existing files.
.TP
.B \-s
Create a symlink.
.TP
.B \-v
Be verbose.
.PP
Note: creating symlinks is not operational at this time.
.\"
.SH SEE ALSO
.BR e2tools (7),
.BR e2mv (1),
.BR e2ls (1),
.BR e2mkdir (1),
.BR e2cp (1),
.BR e2rm (1),
.BR e2tail (1).
.\"
.SH AUTHOR
The \fBe2tools\fP were written by Keith Sheffield <sheff@pobox.com>.
.PP
This manual page was written by Lucas Wall <lwall@debian.org>,
for the Debian project (but may be used by others).
