.TH E2LS 1 "March 2, 2005"
.\"
.SH NAME
e2ls \- list files and directories on an ext2 filesystem
.\"
.SH SYNOPSIS
.B e2ls
.RI [ options ] " file_specification"
.\"
.SH DESCRIPTION
The \fBe2ls\fP command is used to list files and directories on an ext2
filesystem.
.PP
Note: Files deleted via e2rm sometimes will show up even without the -D
option. It is being investigated.
.\"
.SH OPTIONS
.TP
.B \-a
Show hidden directories.
.TP
.B \-c
Sort by creation time (must include -t when using -l).
.TP
.B \-d \fIdir\fP
Open the ext2 filesystem specified by dir.
.TP
.B \-D
Show deleted files bracketed with ><.
.TP
.B \-f
No sorting of the file list.
.TP
.B \-i
Show the inodes (very useful for the -l option).
.TP
.B \-l
Long listing.
.TP
.B \-r
Reverse the sort order.
.TP
.B \-t
Sort by time.
.\"
.SH SEE ALSO
.BR e2tools (7),
.BR e2ln (1),
.BR e2mv (1),
.BR e2mkdir (1),
.BR e2cp (1),
.BR e2rm (1),
.BR e2tail (1).
.\"
.SH AUTHOR
The \fBe2tools\fP were written by Keith Sheffield <sheff@pobox.com>.
.PP
This manual page was written by Lucas Wall <lwall@debian.org>,
for the Debian project (but may be used by others).
