.TH E2MKDIR 1 "March 2, 2005"
.\"
.SH NAME
e2mkdir \- creates a directory on an ext2 filesystem
.\"
.SH SYNOPSIS
.B e2mkdir
.RI [ options ] " directory..."
.\"
.SH DESCRIPTION
The \fBe2mkdir\fP command creates directories on an ext2 filesystem. It
behaves similar to `mkdir -p'.
.\"
.SH OPTIONS
.TP
.B \-G \fIgid\fP
Set the default group to gid.
.TP
.B \-O \fIuid\fP
Set the default file owner to uid.
.TP
.B \-P \fImode\fP
Set the file permissions (ie 755, 666).
.TP
.B \-v
Be verbose.
.\"
.SH SEE ALSO
.BR e2tools (7),
.BR e2ln (1),
.BR e2ls (1),
.BR e2mv (1),
.BR e2cp (1),
.BR e2rm (1),
.BR e2tail (1).
.\"
.SH AUTHOR
The \fBe2tools\fP were written by Keith Sheffield <sheff@pobox.com>.
.PP
This manual page was written by Lucas Wall <lwall@debian.org>,
for the Debian project (but may be used by others).
