.TH E2RM 1 "March 2, 2005"
.\"
.SH NAME
e2rm \- removes files and directories on an ext2 filesystem
.\"
.SH SYNOPSIS
.B e2rm
.RI [ options ] " files..."
.\"
.SH DESCRIPTION
The \fBe2rm\fP command removes files and directories on an ext2 filesystem.
.\"
.SH OPTIONS
.TP
.B \-r
Recursively delete files if a directory name is given.
.TP
.B \-v
Be verbose.
.\"
.SH SEE ALSO
.BR e2tools (7),
.BR e2ln (1),
.BR e2ls (1),
.BR e2mkdir (1),
.BR e2cp (1),
.BR e2mv (1),
.BR e2tail (1).
.\"
.SH AUTHOR
The \fBe2tools\fP were written by Keith Sheffield <sheff@pobox.com>.
.PP
This manual page was written by Lucas Wall <lwall@debian.org>,
for the Debian project (but may be used by others).
