.TH E2TAIL 1 "March 2, 2005"
.\"
.SH NAME
e2tail \- a basic version of the tail command for an ext2 filesystem
.\"
.SH SYNOPSIS
.B e2tail
.RI [ options ] " file"
.\"
.SH DESCRIPTION
The \fBe2tail\fP command implements a basic version of the tail command.
.\"
.SH OPTIONS
.TP
.B \-n \fInum_lines\fP
The number of lines to display
.TP
.B \-f
Output appended data as the file grows.  This is inode dependent, so if the
file is renamed, it will keep checking it.
.TP
.B \-F
Output appended data as the file grows.  This is file name dependent, so if
the file is renamed, it will check on any new files with the same name as the
original.  This is useful for watching log files that may be rotated out
occasionally.  This was requested by a person in the computer security field
for monitoring 'honeypot' type machines.
.TP
.B \-s \fIsleep_interval\fP
The number of seconds to sleep before checking if the file has grown while
in 'follow' mode.  The default is 1.
.\"
.SH SEE ALSO
.BR e2tools (7),
.BR e2ln (1),
.BR e2ls (1),
.BR e2mkdir (1),
.BR e2cp (1),
.BR e2rm (1),
.BR e2mv (1).
.\"
.SH AUTHOR
The \fBe2tools\fP were written by Keith Sheffield <sheff@pobox.com>.
.PP
This manual page was written by Lucas Wall <lwall@debian.org>,
for the Debian project (but may be used by others).
