.TH E2TOOLS 7 "March 2, 2005"
.\"
.SH NAME
e2tools \-  utilities to manipulate files in an ext2/ext3 filesystem
.\"
.SH DESCRIPTION
E2tools is a simple set of GPL'ed utilities to read, write, and
manipulate files in an ext2/ext3 filesystem. These utilities access a
filesystem directly using the ext2fs library. I wrote these tools in order
to copy files into a linux filesystem on a machine that does not have ext2
support. Of course, they can also be used on a linux machine to read/write
to disk images or floppies without having to mount them or have root
access.
.PP
Supported functionality:
.TP
.B e2cp
copy files
.TP
.B e2mv
move files
.TP
.B e2rm
remove files
.TP
.B e2mkdir
create directory
.TP
.B e2ln
create hard links
.TP
.B e2ls
list files/directories
.TP
.B e2tail
output the last part of a file
.PP
In general, to specify a directory or file on an ext2 filesystem for the
e2tools utilities, use the following form:
.IP
filesystem:directory_path
.PP
The filesystem can be an unmounted partition or a regular file that's been
formatted to contain an ext2 filesystem.  In general, if a command takes
multiple file names on the command line, if the first one contains an ext2
file specification, the rest of the files are assumed to be on the same
filesystem until another one is explicitly stated:
.IP
/tmp/boot.img:/tmp/file1
.IP
/tmp/file2
.IP
/tmp/file3
.IP
/tmp/boot2.img:/tmp/file4
.PP
Files 1-3 are on /tmp/boot.img and the last file is on /tmp/boot2.img
.\"
.SH SEE ALSO
.BR e2cp (1),
.BR e2ln (1),
.BR e2ls (1),
.BR e2mkdir (1),
.BR e2mv (1),
.BR e2rm (1),
.BR e2tail (1).
.\"
.SH AUTHOR
The \fBe2tools\fP were written by Keith Sheffield <sheff@pobox.com>.
.PP
This manual page was written by Lucas Wall <lwall@debian.org>,
for the Debian project (but may be used by others).
