.\"	$NetBSD: getconf.1,v 1.13 2014/04/13 01:45:34 snj Exp $
.\"
.\" Copyright (c) 1996 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by J.T. Conklin.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd August 9, 2011
.Dt GETCONF 1
.Os
.Sh NAME
.Nm getconf
.Nd get configuration values
.Sh SYNOPSIS
.Nm
.Ar system_var
.Nm
.Fl a
.Nm
.Ar path_var
.Ar pathname
.Nm
.Fl a
.Ar pathname
.Sh DESCRIPTION
The
.Nm
utility writes the current value of a configurable system limit or
option variable to the standard output.
.Pp
The
.Ar system_var
argument specifies the system variable to be queried.
The names of the system variables are from
.Xr sysconf 3
with the leading
.Dq Li _SC_
removed.
.Pp
The
.Ar path_var
argument specifies the pathname variable to be queried for the specified
.Ar pathname
argument.
The names of the pathname variables are from
.Xr pathconf 2
with the leading
.Dq Li _PC_
removed.
.Pp
When invoked with the option
.Fl a ,
.Nm
writes a list of all applicable variables and their values to the
standard output, in the format
.Do
.Va name
=
.Va value
.Dc .
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr pathconf 2 ,
.Xr confstr 3 ,
.Xr limits 3 ,
.Xr sysconf 3
.Sh STANDARDS
The
.Nm
utility conforms to
.St -p1003.2-92 .
