.\" This is under the same license as uulog itself
.TH UULOG 1
.SH NAME
uulog \- Display the UUCP log file.
.SH SYNOPSIS
.B uulog
[\fI\-n number\fR] [\fI\-sf system\fR] [\fI\-u user\fR] [\fI\-DSF\fR] 
[\fI\-I file\fR] [\fI\-X debug\fR]
.SH DESCRIPTION
.I Uulog
is a program that displays the log file for the Taylor UUCP service.  
.SH OPTIONS
.TP
\fB-n\fR, \fB--lines\fR \fInumber\fR
Show the given number of lines from the end of the log.
.TP
\fB-s\fR, \fB--system\fR \fIsystem\fR
Print entries for the named system.
.TP
\fB-f\fR \fIsystem\fR, \fB--follow\fR=\fIsystem\fR
Follow entries for the named system.
.TP
\fB-u\fR, \fB--user\fR \fIuser\fR
Print entries for the named user.
.TP
\fB-F\fR, \fB--follow\fR
Follow entries for any system.
.TP
\fB-S\fR, \fB--statslog\fR
Show the statistics file.
.TP
\fB-D\fR, \fB--debuglog\fR
Show the debugging file.
.TP
\fB-X\fR, \fB--debug\fR \fIdebug\fR
Set the debugging level.
.TP
\fB-I\fR, \fB--config\fR \fIfile\fR
Set the configuration file to use.
.TP
\fB-v\fR, \fB--version\fR
Print the software version and exit.
.TP
\fB--help\fR
Print a help screen and exit.
.SH BUGS
According to comments in the source, this is a pretty bad implementation 
of uulog.  It only takes a single \-s and/or \-u switch.
.SH "SEE ALSO"
.BR uucp(1) 
.SH AUTHOR
This manual page is a quick write-up for Debian done by Kevin Kreamer 
<kkreamer@etherhogz.org>, by making a manpage out of \fBuulog\fR \fI--help\fR.
