.\" This is under the same license as uuname itself
.TH UUNAME 1
.SH NAME
uuname \- List the names of the known remote UUCP sites.
.SH SYNOPSIS
.B uuname
[\fI\-a\fR] [\fI\-l\fR] [\fI\-I file\fR]
.SH DESCRIPTION
.I Uuname
is a program that lists the names of the known remote UUCP sites.
.SH OPTIONS
.TP
\fB-a\fR, \fB--aliases\fR
Display aliases.
.TP
\fB-l\fR, \fB--local\fR
Print the local name.
.TP
\fB-I\fR, \fB--config\fR \fIfile\fR
Set the configuration file to use.
.TP
\fB-v\fR, \fB--version\fR
Print the software version and exit.
.TP
\fB--help\fR
Print a help screen and exit.
.SH BUGS
None apparent.
.SH "SEE ALSO"
.BR uucp(1) 
.SH AUTHOR
This manual page is a quick write-up for Debian done by Kevin Kreamer 
<kkreamer@etherhogz.org>, by making a manpage out of \fBuuname\fR \fI--help\fR.
