.\" This is under the same license as uupick itself
.TH UUPICK 1
.SH NAME
uupick \- Get files stored in the public directory by uucp \-t.
.SH SYNOPSIS
.B uupick
[\fI\-s system\fR] [\fI\-x debug\fR] [\fI\-I file\fR]
.SH DESCRIPTION
.I Uupick
is a program that gets the files stored in the public directory 
by uucp \-t.
.SH OPTIONS
.TP
\fB-s\fR, \fB--system\fR \fIsystem\fR
Only consider files from named system.
.TP
\fB-x\fR, \fB--debug\fR \fIdebug\fR
Set the debugging level.
.TP
\fB-I\fR, \fB--config\fR \fIfile\fR
Set the configuration file to use.
.TP
\fB-v\fR, \fB--version\fR
Print the software version and exit.
.TP
\fB--help\fR
Print a help screen and exit.
.SH BUGS
None apparent.
.SH "SEE ALSO"
.BR uucp(1) 
.SH AUTHOR
This manual page is a quick write-up for Debian done by Kevin Kreamer 
<kkreamer@etherhogz.org>, by making a manpage out of \fBuupick\fR \fI--help\fR.
