.\" This is under the same license as uusched itself
.TH UUSCHED 8
.SH NAME
uusched \- Call all systems which have work in a random order. 
.SH SYNOPSIS
.B uusched 
.SH DESCRIPTION
.I Uusched
is a program that calls all systems which have work in a random order. 
.SH OPTIONS
Since this a simply a shell script which execs uucico(8), see that manpage 
for further options.
.SH BUGS
None apparent.
.SH "SEE ALSO"
.BR uucico(8),
.BR sh(1)
.SH AUTHOR
This manual page is a quick write-up for Debian done by Kevin Kreamer 
<kkreamer@etherhogz.org>.
