.\" This is under the same license as uuto itself
.TH UUTO 1
.SH NAME
uuto \- Send files to a user on another system.
.SH SYNOPSIS
.B uuto
\fIsystem!user\fR
.SH DESCRIPTION
.I Uuto
is a program that sends files to a user on another system.
.SH OPTIONS
Since this a simply a shell script that execs uucp(1), see that manpage 
for further options.
.SH BUGS
None apparent.
.SH "SEE ALSO"
.BR uucp(1),
.BR sh(1)
.SH AUTHOR
This manual page is a quick write-up for Debian done by Kevin Kreamer 
<kkreamer@etherhogz.org>.
