flags:
  git-annex:
    production: true
    assistant: true
    pairing: true
    torrentparser: true
    webapp: true
    magicmime: false
    dbus: false
    debuglocks: false
    benchmark: false
    networkbsd: false
    gitlfs: true
packages:
- '.'
extra-deps:
 - IfElse-0.85
 - aws-0.22
 - bloomfilter-2.0.1.0
 - filepath-bytestring-1.4.2.1.6
 - git-lfs-1.1.0
 - http-client-restricted-0.0.3
 - network-multicast-0.3.2
 - sandi-0.5
 - torrent-10000.1.1
 - bencode-0.6.1.1
 - network-3.1.0.1
explicit-setup-deps:
  git-annex: true
resolver: lts-16.13
