flags:
  git-annex:
    production: true
    assistant: true
    pairing: true
    torrentparser: true
    webapp: true
    magicmime: false
    dbus: false
    debuglocks: false
    benchmark: true
    gitlfs: true
packages:
  - '.'
resolver: lts-19.0
extra-deps:
  - IfElse-0.85
  - aws-0.22
  - bloomfilter-2.0.1.0
  - git-lfs-1.2.0
  - http-client-restricted-0.0.4
  - network-multicast-0.3.2
  - sandi-0.5
  - torrent-10000.1.1
  - base16-bytestring-0.1.1.7
  - base64-bytestring-1.0.0.3
  - bencode-0.6.1.1
  - aeson-1.5.6.0@sha256:5003bb6fd260d2e2d5a51dee2bf5c8e8f29e4e0e0288fef805c22dcc80ecab06,6788
  - http-client-0.7.11@sha256:3f59ac8ffe2a3768846cdda040a0d1df2a413960529ba61c839861c948871967,5756
explicit-setup-deps:
    git-annex: true
