resolver: lts-14.1
packages:
- .
extra-deps:
- IfElse-0.85
- aws-0.21.1
- bloomfilter-2.0.1.0
- tasty-rerun-1.1.14
- sandi-0.5
flags:
  git-annex:
    magicmime: false
    dbus: false
    torrentparser: false
    networkbsd: false
