flags:
  git-annex:
    production: true
    assistant: true
    pairing: true
    torrentparser: true
    magicmime: false
    dbus: false
    debuglocks: false
    benchmark: true
    gitlfs: true
packages:
- './git-annex-10.20221212'
resolver: lts-20.0
extra-deps:
- IfElse-0.85
- aws-0.23
- ./bloomfilter-2.0.1.0
- git-lfs-1.2.0
- http-client-restricted-0.0.5
- network-multicast-0.3.2
- sandi-0.5
- torrent-10000.1.1
- base16-bytestring-1.0.2.0
- base64-bytestring-1.2.1.0
- bencode-0.6.1.1
- http-client-0.7.13.1
