resolver: lts-12.4
packages:
- .
extra-deps:
- IfElse-0.85
- aws-0.20
- bloomfilter-2.0.1.0
- tasty-rerun-1.1.12
- github: bitemyapp/esqueleto
  commit: 434f81ed41795e3dd0754dbc5c75c4ed098631b3
flags:
  git-annex:
    magicmime: false
    dbus: false
    torrentparser: false
