name: Bug Report
description: File a bug report
labels: ["bug", "needs-testing"]
body:
  - type: markdown
    attributes:
      value: >
        #### Don't request an update of a package,
        [We have a script for that](https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt).
        However, a quality pull request may help.
  - id: verified
    type: dropdown
    attributes:
      label: Is this a new report?
      description: I verified that there isn't already an open issue for this bug
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - id: xuname
    type: input
    attributes:
      label: System Info
      description: Output of `xuname` (part of [`xtools`](https://man.voidlinux.org/xtools.1))
      placeholder: Void 5.x.y_z x86_64-musl ...
    validations:
      required: true
  - id: packages
    type: input
    attributes:
      label: Package(s) Affected
      description: Affected package(s) including version (this can be found with `xbps-query -p pkgver foo`)
      placeholder: foo-1.0.2_5, bar-5.6.7_1, baz-0.0.3_5, ...
    validations:
      required: true
  - id: upstream
    type: textarea
    attributes:
      label: Does a report exist for this bug with the project's home (upstream) and/or another distro?
      description: If so, link it here (It's fine if there's none)
      placeholder: |
        For example:
        https://bugs.kde.org/show_bug.cgi?id=432975
        https://bugs.gentoo.org/767478
  - id: expected
    type: textarea
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen
      placeholder: The package is supposed to do this thing.
    validations:
      required: true
  - id: description
    type: textarea
    attributes:
      label: Actual behaviour
      description: A clear and concise description of what the bug is
      placeholder: There was a crash when...
    validations:
      required: true
  - id: steps
    type: textarea
    attributes:
      label: Steps to reproduce
      description: Clear steps to reproduce the bug
      placeholder: |
        1. Do the thing
        2. Do the other thing
        3. ???
        4. Crash :(
    validations:
      required: true
