name: Package Request
title: "Package request: "
description: Request the addition of a package
labels: ["request"]
body:
  - type: markdown
    attributes:
      value: >
        #### Don't request an update of a package,
        [We have a script for that](https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt).
        However, a quality pull request may help.
  - id: name
    type: input
    attributes:
      label: Package name
      placeholder: foobar9k
    validations:
      required: true
  - id: homepage
    type: input
    attributes:
      label: Package homepage
      placeholder: https://example.com/foobar9k
    validations:
      required: true
  - id: description
    type: textarea
    attributes:
      label: Description
      description: What does the package do?
      placeholder: >
        Foobar9k is a music player that turns your music up to 11.
        It provides features X, Y, and Z, which other music players in Void don't.
    validations:
      required: true
  - id: quality
    type: dropdown
    attributes:
      label: Does the requested package meet the quality requirements?
      description: |
        See [Manual.md](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality_requirements) for details
      multiple: true
      options:
        - System
        - Compiled
        - Required
    validations:
      required: true
  - id: released
    type: dropdown
    attributes:
      label: Is the requested package released?
      description: |
        See [Manual.md](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality_requirements) for details
      options:
        - "Yes"
        - "No"
    validations:
      required: true
