resolver: lts-16.20

packages:
  - ./pandoc-2.10.1
  - ./pandoc-citeproc-0.17.0.1
  - ./pandoc-sidenote-0.20.0

flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
    static: false
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false

extra-deps:
  - pandoc-types-1.21
  - haddock-library-1.9.0
  - regex-pcre-builtin-0.95.1.2.8.43
  - hslua-1.1.2
  - jira-wiki-markup-1.3.2
  - commonmark-0.1.0.1
  - commonmark-extensions-0.2.0.0
  - commonmark-pandoc-0.2.0.0

ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
