resolver: lts-17.9

packages:
  - ./pandoc-2.11.4
  - ./pandoc-sidenote-0.20.0

flags:
  pandoc:
    trypandoc: false
    embed_data_files: true

extra-deps:
  - pandoc-types-1.22
  - haddock-library-1.9.0
  - regex-pcre-builtin-0.95.2.3.8.43
  - hslua-1.2.0
  - jira-wiki-markup-1.3.4
  - commonmark-0.1.1.4
  - commonmark-extensions-0.2.0.4
  - commonmark-pandoc-0.2.0.1

ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
