--- a/Makefile	2016-12-06 21:40:22.715155552 +0100
+++ b/Makefile	2016-12-06 21:41:39.523155740 +0100
@@ -50,12 +50,8 @@
 
 FE_VERSION=v2.2.0
 
-CC=gcc
-CXX=g++
 CFLAGS=$(EXTRA_CFLAGS)
-STRIP=strip
 PKG_CONFIG=pkg-config
-AR=ar
 ARFLAGS=rc
 RM=rm -f
 MD=mkdir -p
@@ -84,7 +84,7 @@
 override WINDRES := $(TOOLCHAIN)-$(WINDRES)
 endif
 
-prefix=/usr/local
+prefix=/usr
 datarootdir=$(prefix)/share
 datadir=$(datarootdir)
 exec_prefix=$(prefix)
@@ -414,7 +414,7 @@
 
 $(EXE): $(OBJ) $(EXPAT) $(SQUIRREL) $(AUDIO)
 	$(EXE_MSG)
-	$(SILENT)$(CXX) -o $@ $^ $(CFLAGS) $(FE_FLAGS) $(LIBS)
+	$(SILENT)$(CXX) -o $@ $^ $(LDFLAGS) $(CFLAGS) $(FE_FLAGS) $(LIBS)
 ifneq ($(FE_DEBUG),1)
 	$(SILENT)$(STRIP) $@
 endif
