On March 15, 2021, Google will be limiting access to their private Chrome APIs:

    https://blog.chromium.org/2021/01/limiting-private-api-availability-in.html

This means that after this date, chromium users will no longer be able to take
advantage of features such as Google account sync (including bookmarks), spell
checking, translation, and safe browsing. These features will only be available
with the restricted google-chrome package.
