# vim: set ts=4 sw=4 et:
#
# This hook executes the following tasks:
#   - Looks on all packages for *.orig files generated by patch on fuzzy match

hook() {
    local matches mime file f prune_expr dir

    while read -r file; do
        basename="${file%.orig}"
        if [ -f "$basename" ]; then
            if [ -z "$matches" ]; then
                matches=yes
                msg_red "Fuzzy patches generate those files:\n"
            fi
            msg_red "    $file\n"
        fi
    done < <(find $PKGDESTDIR -type f -name '*.orig')
    if [ "$matches" ]; then
        msg_error "Please refresh the patches\n"
    fi
}
