NOTICE:

Please maintain a backup of your old saved games.

Tilesets for 0.47 are only partially supported by the new
version (0.50.10). If you still want to use the 0.47 tilesets
copy the 'art' and 'init' directories from your tileset to
/home/user/.local/share/dwarffortress/data/

In your game settings video option, make sure
'Use Classic ASCII glyphs' is switched to 'Yes', in order to
avoid your game displaying with missing graphic assets.

If you have purchased the game on itch or Steam,
you can also replace ~/.local/share/dwarffortress/data
directory with the one from your purchased version then turn off the ASCII glypjs.