Some optional packages must be installed for additional functionality:

 - unrar: for automatic extraction of rar archives

By default, SABnzbd will listen on 127.0.0.1:8080 - This can be
changed with the -s option. See 'sabnzbd --help' for more information
on configuration directives.

All SABnzbd settings are stored in \$HOME/.sabnzbd. Editing global
configuration files should not be necessary.
