#!/bin/sh

_user=_speakersafetyd
! [ -d /run/speakersafetyd ] && install -m 700 -g $_user -o $_user -d /run/speakersafetyd
chown -R $_user:$_user /run/speakersafetyd

_caps=-all,+sys_nice

exec 2>&1
exec setpriv --reuid $_user --regid audio --clear-groups \
  --ambient-caps $_caps \
  --inh-caps $_caps \
  --bounding-set $_caps \
  --no-new-privs -- speakersafetyd -c /usr/share/speakersafetyd/ -b /var/lib/speakersafetyd/blackbox -m 7
