[book]
authors = ["The Void Linux Team"]
multilingual = false
src = "src"
title = "XBPS Source Packages Manual"

[preprocessor.gen_manual]
command = "python3 generate_mdbook.py"

[output.html]
# TODO: this should be a submodule or something
# to avoid de-syncing with void-docs/src/theme
theme = "src/theme"
default-theme = "void-light"
preferred-dark-theme = "void-dark"
edit-url-template = "https://github.com/void-linux/void-packages/edit/master/Manual.md"
limit-results = 100
