.TH INITRAMFS.CONF 5  "2012/01/13" "Linux" "initramfs.conf manual"

.SH NAME
initramfs.conf \- configuration file for mkinitramfs

.SH DESCRIPTION
The behaviour of
.B mkinitramfs
can be modified by its configuration file.

Each line in the file can be a configuration variable, a blank line,
or a comment. The value of an variable is assigned by an statement
of the form: \fIname\fP=[\fIvalue\fP]

Configuration options can be broken out into configuration snippets and
placed in individual files in the /etc/mkinitramfs/conf.d directory.  Files
in this directory are always read \fBafter\fP the main configuration file,
so you can override the settings in the main config file without editing it
directly.

.SH GENERAL VARIABLES
.TP
\fB MODULES
Specifies the modules for the initramfs image.

Modules listed in \fI/etc/initramfs-tools/modules\fP and
\fI/usr/share/initramfs-tools/modules.d/*\fP are always included in the
initramfs, and are loaded early in the boot process.


\fIlist\fP doesn't load any additional modules at boot time, other than those
listed in the above files.

\fImost\fP adds most file system, all ata, sata, scsi and usb drivers.

\fIdep\fP tries to guess which modules are necessary for the running box and
only adds those modules.

The default setting is \fImost\fP.

.TP
\fB KEYMAP
If set to 'y', the console keymap will be loaded during the initramfs stage.
The keymap will anyway be loaded by the initscripts later, and the packages
that might need input will normally set this variable automatically, so there
should normally be no need to set this.

.TP
\fB COMPRESS
Specifies the compression method used for the initramfs image.
.B mkinitramfs
will default to gzip if the kernel lacks support (CONFIG_RD) or the
corresponding userspace utility is not present.

.TP
\fB UMASK
Set the umask value of the generated initramfs file.
Useful to not disclose eventual keys.

.SH FILES
.TP
.I /etc/initramfs-tools/initramfs.conf

.SH AUTHOR
The initramfs-tools are written by Maximilian Attems <maks@debian.org>,
Jeff Bailey <jbailey@raspberryginger.com> and numerous others.
Loosely based on mkinitrd.conf by Herbert Xu.

.SH SEE ALSO
.BR
.IR initramfs-tools (8),
.IR mkinitramfs (8),
.IR update-initramfs (8).
