.TH LSINITRAMFS 8  "2010/06/16" "Linux" "lsinitramfs manual"

.SH NAME
lsinitramfs \- list content of an initramfs image

.SH SYNOPSIS
.B lsinitramfs
.RI [ options ] " <initramfsfile> " [ <initramfsfile> ]
.br

.SH DESCRIPTION
The
.B lsinitramfs
command lists the content of given initramfs images. It allows to quickly check
the content of one (or multiple) specified initramfs files.

.SH OPTIONS

.TP
.B -h
Display usage information and exit.

.TP
.B -l
Display long and more verbose listing of initramfs content.

.SH USAGE EXAMPLES

List initramfs content of current running kernel:

.PP
.B lsinitramfs /boot/initrd.img-$(uname -r)

List content of two initramfs files in verbose mode:

.PP
.B lsinitramfs -l /boot/vmlinuz-2.6.31-grml64 /boot/vmlinuz-2.6.33-grml64

.SH AUTHOR
The initramfs-tools are written by Maximilian Attems <maks@debian.org>
and numerous others.

.SH SEE ALSO
.BR
.IR initramfs-tools (8),
.IR mkinitramfs (8),
.IR update-initramfs (8).
