.TH UPDATE-INITRAMFS.CONF 5  "2010/04/05" "Linux" "update-initramfs.conf manual"

.SH NAME
update-initramfs.conf \- configuration file for update-initramfs

.SH DESCRIPTION
The configuration file allows to disable the update action from
.B update-initramfs.

.SH GENERAL VARIABLES
.TP
\fB update_initramfs
Default is \fIyes\fP for running the latest initramfs-tools hooks in the
newest Linux image.
Setting it to \fIall\fP updates any known initramfs.
It is possible to set it to \fIno\fP for remote servers or boxes where
conservative manners needs to be applied. This disables
the \fBupdate_initramfs \-u\fP call.
.TP
\fB backup_initramfs
If set \fBupdate_initramfs\fP keeps an .bak file of the previous initramfs. If unset the backup initramfs will not be kept.

.SH FILES
.TP
.I /etc/initramfs-tools/update-initramfs.conf

.SH AUTHOR
The initramfs-tools are written by Maximilian Attems <maks@debian.org>,
Jeff Bailey <jbailey@raspberryginger.com> and numerous others.
.SH SEE ALSO
.BR
.IR initramfs.conf (5),
.IR initramfs-tools (8),
.IR mkinitramfs (8),
.IR update-initramfs (8).
