.TH MAELSTROM "6" "April 2009" "Ambrosia Software" "Games"
.SH NAME
Maelstrom \- Enhanced Asteroids\-like game
.SH SYNOPSIS
.B Maelstrom
[\-netscores] \-printscores
.P
.B Maelstrom
[options]
.P
.B Maelstrom\-netd
.br
\fI(see NETWORKING, below, for a description of Maelstrom\-netd)\fR
.SH DESCRIPTION
Maelstrom is a game based on Asteroids, but with several gameplay enhancements:
.P
\- High\-resolution color graphics
.br
\- Digital audio
.br
\- Powerups
.br
\- Networked multiplayer/deathmatch mode (up to 3 players)
.br
\- World\-wide high score server
.P
Game storyline:
.br
You pilot your ship through the dreaded "Maelstrom" asteroid belt \-\-
suddenly your best friend thrusts towards you and fires, directly at your
cockpit. You raise your shields just in time, and the battle is joined.
.P
The deadliest stretch of space known to mankind has just gotten
deadlier. Everywhere massive asteroids jostle for a chance to crush your
ship, and deadly shinobi fighter patrols pursue you across the asteroid
belt. But the deadliest of them all is your sister ship, assigned to
you on patrol. The pilot, trained by your own Navy, battle hardened by
months in the Maelstrom, is equipped with a twin of your own ship and
intimate knowledge of your tactics.
.P
The lovely Stratocaster R&R facility never sounded so good, but as you
fire full thrusters to dodge the latest barrage you begin to think you'll
never get home...
.SH OPTIONS
.TP
\fB\-fullscreen\fR
Run Maelstrom in full\-screen mode. You may also press Alt\-Enter
while Maelstrom is running, to toggle full\-screen.
.TP
\fB\-gamma\fR [0\-8]
Set the gamma correction
.TP
\fB\-volume\fR [0\-8]
Set the sound volume
.TP
\fB\-netscores\fR
Use the world\-wide network score server
.TP
\fB\-player\fR N[@host][:port]
Designate player N (at host and/or port). N must be an integer, 1 to 3.
.TP
\fB\-server\fR N@host[:port]
Play with N players using server at host. N must be an integer, 1 to 3.
.TP
\fB\-deathmatch\fR [N]
Play deathmatch to N frags (default = 8)
.SH CONTROLS
The game may be played with either the keyboard or a joystick.
The game controls may be remapped by pressing C at the main menu. The
default keyboard controls are:
.TP
\fBTab\fR, \fBJoystick Button 1\fR
Fire
.TP
\fBUp Arrow\fR, \fBJoystick Up\fR
Thrust
.TP
\fBSpace\fR, \fBJoystick Button 2\fR
Shield
.TP
\fBRight Arrow\fR, \fBJoystick Right\fR
Turn Clockwise
.TP
\fBLeft Arrow\fR, \fBJoystick Left\fR
Turn Counter\-clockwise
.TP
\fBP\fR
Pause
.TP
\fBEscape\fR
Abort Game
.TP
\fBAlt\-Enter\fR
Toggle between fullscreen and windowed modes. This keystroke
may not be remapped.
.P
No special configuration must be done to play with a joystick, provided
the joystick is supported by the SDL library on your OS.
There is no way
to remap the joystick controls.
.SH NETWORKING
.SS Netplay Without a Server
Networking has been tested on Linux, SGI and DEC.  It is known to
work between SGI and DEC systems (cross\-platform), and between systems
of the same type.
.P
Up to three players can play, and the syntax is as follows:
.P
(On machine 1)
.br
.B
.nh
Maelstrom \-player 1 \-player 2@machine2 \-player 3@machine3
.hy
.P
(On machine 2)
.br
.B
.nh
Maelstrom \-player 1@machine1 \-player 2 \-player 3@machine3
.hy
.P
(On machine 3)
.br
.B
.nh
Maelstrom \-player 1@machine1 \-player 2@machine2 \-player 3
.hy
.SS Netplay With a Server
You can also use a network address server that handles the difficulties
of getting all the players and addresses right.  The address server is
installed as \fBMaelstrom\-netd\fR, and if run on say "servhost", the syntax
for a three player game would be:
.P
(On machine A)
.br
.B
.nh
Maelstrom \-player 1 \-server 3@servhost
.hy
.P
(On machine B)
.br
.B
.nh
Maelstrom \-player 2 \-server 3@servhost
.hy
.P
(On machine C)
.br
.B
.nh
Maelstrom \-player 3 \-server 3@servhost
.hy
.P
The address server will let players know if they have conflicting
player numbers, and will set up the proper addresses for all players.
It can field multiple games, and can be a "game hub" where a bunch
of players can get together for romping network games. :)
.P
\fBNOTE\fR: Maelstrom-netd will not run correctly on 64\-bit hosts,
and Maelstrom running on a 64\-bit host cannot successfully play in a
mutiplayer game with the -server option. Use non\-server networked
play mode instead.
.SS Network Ports
By default, Maelstrom uses UDP ports 44718 to 44720 for networked games,
where the port number is the player number plus 44717.
(these may be overridden with the \fI:port\fR syntax, above).
.P
\fBMaelstrom-netd\fR listens on TCP port 44717.
.P
The global
high\-score server listens on the host \fBdevolution.com\fR, TCP port 4444.
.SH ADD\-ONS
Maelstrom add\-ons consist of replacement sounds, replacement sprites,
or both. Typically, the add\-on content is distributed as a zip file.
.P
There is a collection of Maelstrom add\-on content at
.br
.nh
\fIhttp://www.devolution.com/~slouken/Maelstrom/add-ons.html\fR
.hy
.SS Automated Installation (Preferred)
Use \fBmaelstrom_addon_package.pl\fR to convert the zip
file to a Slackware package, then use \fBinstallpkg\fR to install the
add\-on. Run \fBmaelstrom_addon_package.pl \-\-help\fR for more information.
.SS Manual Installation
Look within the zip file for files named
\fI%Maelstrom_Sprites\fR and/or \fI%Maelstrom_Sounds\fR or similar
(the % may be missing, the _ may be a space, and/or the filenames
may end with .bin). Copy these files to
.P
.nh
\fB/usr/share/games/Maelstrom/%Maelstrom_Sprites\fR
.br
and/or
.br
\fB/usr/share/games/Maelstrom/%Maelstrom_Sounds\fR
.hy
.P
\fBNOTE\fR: \fIThe % is important!\fR
.SS Add\-On Limitations
There is no way to install more than one add\-on at a time, or to disable
the installed add\-on without uninstalling it. There is also no way to
install add\-ons in a user's home directory, or any other place than
the system\-wide game data directory.
.SH FILES
.TP
\fB/usr/share/games/Maelstrom/\fR
game data (images, music, sound)
.TP
\fB$HOME/.Maelstrom\-data\fR
per\-user settings and high\-score records
.SH AUTHORS
The original version of this game was written for the Macintosh by
Andrew Welch, of Ambrosia Software.  It was ported to Linux and then
to the Simple DirectMedia Layer library by Sam Lantinga.
.P
Man page created by B. Watson for SlackBuilds.org project (but others
are free to use it)
.SH COPYRIGHT
The source code to Maelstrom 3.0 and higher has been released under
the GNU General Public License which can be found in COPYING.GPL.
.P
The artwork and sounds used by Maelstrom are copyright Ambrosia Software
(http://www.ambrosiasw.com) and may not be redistributed separately from
the Maelstrom GPL source code.
