# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).

set( HAVE_PRINTF_Z_EXITCODE
     0
     CACHE INTERNAL "Result from TRY_RUN" FORCE)

