# Hide the direct libcamera node. It shows black, apps use the relay instead.
monitor.libcamera.rules = [
  {
    matches = [
      { device.name = "~libcamera_device.*" }
    ]
    actions = {
      update-props = {
        device.disabled = true
      }
    }
  }
]
