# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# ALLEGRO_USE_CONSTRUCTOR_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set ALLEGRO_USE_CONSTRUCTOR_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# ALLEGRO_USE_CONSTRUCTOR_EXITCODE__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set ALLEGRO_USE_CONSTRUCTOR_EXITCODE__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The ALLEGRO_USE_CONSTRUCTOR_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /builddir/allegro-4.4.3.1/build/CMakeFiles/CMakeTmp/src.c
# Executable    : /builddir/allegro-4.4.3.1/build/CMakeFiles/cmTC_80441-ALLEGRO_USE_CONSTRUCTOR_EXITCODE
# Run arguments : 
#    Called from: [2]	/usr/share/cmake-3.16/Modules/CheckCSourceRuns.cmake
#                 [1]	/builddir/allegro-4.4.3.1/CMakeLists.txt

set( ALLEGRO_USE_CONSTRUCTOR_EXITCODE 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( ALLEGRO_USE_CONSTRUCTOR_EXITCODE__TRYRUN_OUTPUT 
     "0"
     CACHE STRING "Output from TRY_RUN" FORCE)

