bindaddress = "[::]:8443"
ldapbindaddress = "[::]:3636"
db_path = "/var/lib/kanidm/kanidm.db"

domain = "idm.example.com"
origin = "https://idm.example.com:8443"

tls_chain = "/etc/kanidm/chain.pem"
tls_key = "/etc/kanidm/key.pem"

log_level = "info"
