# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# RUN_RESULT
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set RUN_RESULT to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# RUN_RESULT__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set RUN_RESULT__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The COMPILE_SUCCEEDED variable holds the build result for this TRY_RUN().
# 
# Source file   : /builddir/vigra-Version-1-11-0/config/output_cplusplus_version.cxx
# Executable    : /builddir/vigra-Version-1-11-0/build/CMakeFiles/cmTryCompileExec2883594344-RUN_RESULT
# Run arguments : 
#    Called from: [1]	/builddir/vigra-Version-1-11-0/CMakeLists.txt

set( RUN_RESULT 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( RUN_RESULT__TRYRUN_OUTPUT 
     "%OUTPUT%"
     CACHE STRING "Output from TRY_RUN" FORCE)

