.TH INITRAMFS.CONF 5  "2008/12/19" "Linux" "initramfs.conf manual"

.SH NAME
initramfs.conf \- configuration file for mkinitramfs

.SH DESCRIPTION
The behaviour of
.B mkinitramfs
can be modified by its configuration file.

Each line in the file can be a configuration variable, a blank line,
or a comment. The value of an variable is assigned by an statement
of the form: \fIname\fP=[\fIvalue\fP]

Configuration options can be broken out into configuration snippets and
placed in individual files in the /etc/mkinitramfs/conf.d directory.  Files
in this directory are always read \fBafter\fP the main configuration file,
so you can override the settings in the main config file without editing it
directly.

.SH GENERAL VARIABLES
.TP
\fB MODULES
Specifies the modules for the initramfs image.
The default setting is \fImost\fP.

\fImost\fP adds all the framebuffer, acpi, file system, ide, sata, scsi and usb drivers.

\fIdep\fP tries to guess which modules are necessary for the running box.

\fInetboot\fP adds the base modules, network modules, but skips block devices.

\fIlist\fP includes only modules from the additional modules list to load them
early.

.TP
\fB BUSYBOX
Include busybox utilities for the boot scripts.
If set to 'n'
.B mkinitramfs
will build an initramfs without busybox.
Beware that many boot scripts need busybox utilities.

.TP
\fB KEYMAP
If set to 'y', the console keymap will be loaded during the initramfs stage.
The keymap will anyway be loaded by the initscripts later, and the packages
that might need input will normally set this variable automatically, so there
should normally be no need to set this.

.SH NFS VARIABLES
.TP
\fB BOOT
Allows to use an nfs drive as the root of the drive.
The default is to boot from \fIlocal\fP media (hard drive, USB stick).
Set to \fInfs\fP for an NFS root share.

.TP
\fB DEVICE
Specifies the network interface, like eth0.

.TP
\fB ROOT
Allows optional root bootarg hardcoding, when no root bootarg can be passed.
A root bootarg overrides that special setting.

.TP
\fB NFSROOT
Defaults to \fIauto\fP in order to pick up value from DHCP server.
Otherwise you need to specify \fIHOST:MOUNT\fP.


.SH AUTHOR
The initramfs-tools are written by Maximilian Attems <maks@debian.org>,
Jeff Bailey <jbailey@raspberryginger.com> and numerous others.
Loosely based on mkinitrd.conf by Herbert Xu.

.SH SEE ALSO
.BR
.IR initramfs-tools (8),
.IR mkinitramfs (8),
.IR update-initramfs (8).
