.TH UPDATE-INITRAMFS 8  "2008/12/19" "Linux" "update\-initramfs manual"

.SH NAME
update\-initramfs \- generate an initramfs image

.SH SYNOPSIS
.B update\-initramfs
.RB  \-c | \-d | \-u
.RB [ \-k
.IR version ]
.RB [ \-t ]
.RB [ \-v ]
.RB [ \-b ]
.RB [ \-h ]
.SH DESCRIPTION
The
.B update\-initramfs
script manages your initramfs images on your local box.
It keeps track of the existing initramfs archives in /boot.
There are three modes of operation create, update or delete.
You must at least specify one of those modes.

The initramfs is a gzipped cpio archive.
At boot time, the kernel unpacks that archive into RAM disk, mounts and
uses it as initial root file system. All finding of the root device
happens in this early userspace.

.SH OPTIONS
.TP
\fB \-k \fI version
Set the specific kernel version for whom the initramfs will be generated.
For example the output of uname \-r for your currently running kernel.
This argument is optional for update. The default is the latest kernel version.

The use of "all" for the
.I version
string specifies
.B update\-initramfs
to execute the chosen action for all kernel versions, that are already known
to
.B update\-initramfs.

.TP
\fB \-c
This mode creates a new initramfs.

.TP
\fB \-u
This mode updates an existing initramfs.

.TP
\fB \-d
This mode removes an existing initramfs.

.TP
\fB \-t
Allows to take over an custom initramfs with a newer one.

.TP
\fB \-v
This option increases the amount of information you are given during
the chosen action.

.TP
\fB \-b
Set an different bootdir for the image creation.

.TP
\fB \-h
Print a short help page describing the available options in
.B update\-initramfs.

.SH EXAMPLES

Update the initramfs of the newest kernel:

.PP
.B update\-initramfs -u


Create the initramfs for a specific kernel:

.PP
.B update\-initramfs -c -k 2.6.18-1-686

.SH FILES
/etc/initramfs-tools/update-initramfs.conf

.SH AUTHOR
The initramfs-tools are written by Maximilian Attems <maks@debian.org>,
Jeff Bailey <jbailey@raspberryginger.com> and numerous others.

.SH SEE ALSO
.BR
.IR initramfs.conf (5),
.IR initramfs-tools (8),
.IR mkinitramfs (8).
