# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# _correct_iconv_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set _correct_iconv_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The _correct_iconv_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /builddir/evolution-data-server-3.26.0/build/CMakeFiles/CMakeTmp/src.c
# Executable    : /builddir/evolution-data-server-3.26.0/build/CMakeFiles/cmTC_315ee-_correct_iconv_EXITCODE
# Run arguments : 
#    Called from: [2]	/usr/share/cmake-3.9/Modules/CheckCSourceRuns.cmake
#                 [1]	/builddir/evolution-data-server-3.26.0/CMakeLists.txt

set( _correct_iconv_EXITCODE 
     0
     CACHE INTERNAL "Result from TRY_RUN" FORCE)
set(_correct_iconv_EXITCODE__TRYRUN_OUTPUT
     0
     CACHE INTERNAL "Result from TRY_RUN" FORCE)


# HAVE_LKSTRFTIME_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HAVE_LKSTRFTIME_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The HAVE_LKSTRFTIME_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /builddir/evolution-data-server-3.26.0/build/CMakeFiles/CMakeTmp/src.c
# Executable    : /builddir/evolution-data-server-3.26.0/build/CMakeFiles/cmTC_d2897-HAVE_LKSTRFTIME_EXITCODE
# Run arguments : 
#    Called from: [2]	/usr/share/cmake-3.9/Modules/CheckCSourceRuns.cmake
#                 [1]	/builddir/evolution-data-server-3.26.0/CMakeLists.txt

set( HAVE_LKSTRFTIME_EXITCODE 
     0
     CACHE INTERNAL "Result from TRY_RUN" FORCE)
set( HAVE_LKSTRFTIME_EXITCODE__TRYRUN_OUTPUT
     0
     CACHE INTERNAL "Result from TRY_RUN" FORCE)

