.Dd 2004-04-09
.Dt IFENSLAVE 8
.Os "Debian GNU/Linux"
.\" Manual page created by Guus Sliepen <guus@debian.org>
.Sh NAME
.Nm ifenslave
.Nd Attach and detach slave network devices to a bonding device.
.Sh SYNOPSIS
.Nm
.Op Fl acdfhuvV
.Op Fl -all-interfaces
.Op Fl -change-active
.Op Fl -detach
.Op Fl -force
.Op Fl -help
.Op Fl -usage
.Op Fl -verbose
.Op Fl -version
.Ar master
.Ar slave
.No ...
.Sh DESCRIPTION
.Nm
is a tool to attach and detach slave network devices to a bonding device.
A bonding device will act like a normal Ethernet network device to the kernel,
but will send out the packets via the slave devices using a simple round-robin scheduler.
This allows for simple load-balancing,
identical to "channel bonding" or "trunking" techniques used in switches.
.Pp
The kernel must have support for bonding devices for
.Nm
to be useful.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl a, -all-interfaces
Show information about all interfaces.
.It Fl c, -change-active
Change active slave.
.It Fl d, -detach
Removes slave interfaces from the bonding device.
.It Fl f, -force
Force actions to be taken if one of the specified interfaces appears not to belong to an Ethernet device.
.It Fl h, -help
Display a help message and exit.
.It Fl u, -usage
Show usage information and exit.
.It Fl v, -verbose
Print warning and debug messages.
.It Fl V, -version
Show version information and exit.
.El
If not options are given, the default action will be to enslave interfaces.
.Sh EXAMPLE
The following example shows how to setup a bonding device and
enslave two real Ethernet devices to it:
.Bd -literal
# modprobe bonding
# ifconfig bond0 192.168.0.1 netmask 255.255.0.0
# ifenslave bond0 eth0 eth1
.Ed
.Sh AUTHOR
.Nm
was originally written by
.An Donald Becker Aq becker@cesdis.gsfc.nasa.gov ,
and has since been updated by various kernel developers.
.Pp
This manual page was written by
.An Guus Sliepen Aq guus@debian.org
for the Debian GNU/Linux system.
