name: 'Scheduled tasks'

on:
  schedule:
    - cron: '0 18 * * *'

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v2
        with:
          github-token: ${{ github.token }}
          pr-lock-inactive-days: '90'
          process-only: 'prs'
  cycles:
    runs-on: ubuntu-latest
    steps:
      - run: apt-get install -y python3-networkx
      - run: common/scripts/xbps-cycles.py
