name: 'Scheduled tasks'

on:
  schedule:
    - cron: '0 18 * * *'

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v2
        with:
          github-token: ${{ github.token }}
          pr-lock-inactive-days: '90'
          process-only: 'prs'
  cycles:
    runs-on: ubuntu-latest
    container:
        image: 'ghcr.io/void-linux/xbps-src-masterdir:20210313rc01-x86_64-musl'
    steps:
      - name: Prepare container
        run: |
          # Sync and upgrade once, assume error comes from xbps update
          xbps-install -Syu || xbps-install -yu xbps
          # Upgrade again (in case there was a xbps update)
          xbps-install -yu
          # Install script dependencies
          xbps-install -y python3-networkx github-cli
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Create hostrepo and prepare masterdir
        run: |
         ln -s "$(pwd)" /hostrepo &&
         common/travis/set_mirror.sh &&
         common/travis/prepare.sh
      - name: Find cycles and open issues
        run: |
         common/scripts/xbps-cycles.py | tee cycles
         grep 'Cycle:' cycles | while read -r line; do
             if gh issue list -R "$GITHUB_REPOSITORY" -S "$line" | grep .; then
                 printf "Issue on '%s' already exists.\n" "$line"
             else
                 gh issue create -R "$GITHUB_REPOSITORY" -b '' -t "$line"
             fi
         done
        env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
