name: "Issue Notification"
on:
  issues:
    types: [opened, closed]

jobs:
  ircnotify:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Shorten URL
        id: shortener
        if: github.repository == 'void-linux/void-packages'
        uses: Gottox/url-shortener-action@master
        with:
          url: "${{ github.event.issue.html_url }}"
      - name: "Issue Notification"
        uses: Gottox/irc-message-action@main
        continue-on-error: true
        if: github.repository == 'void-linux/void-packages'
        with:
          channel: "#xbps"
          nickname: void-packages
          sasl_password: ${{ secrets.freenode_password_void_packages }}
          tls: true
          message: >-
            ${{ github.actor }}
            ${{ github.event.action }} issue
            #${{ github.event.issue.number }}
            “${{ github.event.issue.title }}”
            ${{ steps.shortener.outputs.short_url }}
