---
name: Stale Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: 'Issues become stale 90 days after last activity and are closed 7 days after that.  If this issue is still relevant bump it or assign it.'
          stale-pr-message: 'Pull Requests become stale 90 days after last activity and are closed 7 days after that.  If this pull request is still relevant bump it or assign it.'
          days-before-stale: 90
          days-before-close: 7
          debug-only: true
          exempt-all-assignees: true
          operations-per-run: 1000
