name: Trigger repository build

on:
  push:
    branches:
      - wagnerflo

jobs:
  trigger:
    name: Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: wagnerflo/void-repository
          event-type: Push to wagnerflo/void-packages
