IMPORTANT NOTE
--------------
If you want to use this emulator properly, you need to grab original 
Atari ROM files. You can extract them from official XFormer 2000  
emulator distribution, located on Atari800 sourceforge repo:
http://downloads.sourceforge.net/project/atari800/ROM/Original%20XL%20ROM/xf25.zip
Just extract .ROM files from given .ZIP archive and point your Atari800 
emulator to directory with them using F1 => Emulator Configuration => 
System ROM Settings.

Have fun.
