# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_wayle_global_optspecs
	string join \n h/help V/version
end

function __fish_wayle_needs_command
	# Figure out if the current invocation already has a command.
	set -l cmd (commandline -opc)
	set -e cmd[1]
	argparse -s (__fish_wayle_global_optspecs) -- $cmd 2>/dev/null
	or return
	if set -q argv[1]
		# Also print the command, so this can be used to figure out what it is.
		echo $argv[1]
		return 1
	end
	return 0
end

function __fish_wayle_using_subcommand
	set -l cmd (__fish_wayle_needs_command)
	test -z "$cmd"
	and return 1
	contains -- $cmd[1] $argv
end

complete -c wayle -n "__fish_wayle_needs_command" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_needs_command" -s V -l version -d 'Print version'
complete -c wayle -n "__fish_wayle_needs_command" -f -a "audio" -d 'Audio control commands'
complete -c wayle -n "__fish_wayle_needs_command" -f -a "config" -d 'Configuration management commands'
complete -c wayle -n "__fish_wayle_needs_command" -f -a "icons" -d 'Icon management commands'
complete -c wayle -n "__fish_wayle_needs_command" -f -a "media" -d 'Media player control commands'
complete -c wayle -n "__fish_wayle_needs_command" -f -a "notify" -d 'Notification control commands'
complete -c wayle -n "__fish_wayle_needs_command" -f -a "panel" -d 'Panel management commands'
complete -c wayle -n "__fish_wayle_needs_command" -f -a "power" -d 'Power profile commands'
complete -c wayle -n "__fish_wayle_needs_command" -f -a "systray" -d 'System tray commands'
complete -c wayle -n "__fish_wayle_needs_command" -f -a "wallpaper" -d 'Wallpaper control commands'
complete -c wayle -n "__fish_wayle_needs_command" -f -a "idle" -d 'Idle inhibit control commands'
complete -c wayle -n "__fish_wayle_needs_command" -f -a "shell" -d 'Run the desktop shell in the foreground'
complete -c wayle -n "__fish_wayle_needs_command" -f -a "completions" -d 'Generate shell completions'
complete -c wayle -n "__fish_wayle_needs_command" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and not __fish_seen_subcommand_from output-volume output-mute input-volume input-mute sinks sources status help" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and not __fish_seen_subcommand_from output-volume output-mute input-volume input-mute sinks sources status help" -f -a "output-volume" -d 'Get or set output volume level'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and not __fish_seen_subcommand_from output-volume output-mute input-volume input-mute sinks sources status help" -f -a "output-mute" -d 'Toggle output mute state'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and not __fish_seen_subcommand_from output-volume output-mute input-volume input-mute sinks sources status help" -f -a "input-volume" -d 'Get or set input volume level'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and not __fish_seen_subcommand_from output-volume output-mute input-volume input-mute sinks sources status help" -f -a "input-mute" -d 'Toggle input mute state'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and not __fish_seen_subcommand_from output-volume output-mute input-volume input-mute sinks sources status help" -f -a "sinks" -d 'List available audio sinks (outputs)'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and not __fish_seen_subcommand_from output-volume output-mute input-volume input-mute sinks sources status help" -f -a "sources" -d 'List available audio sources (inputs)'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and not __fish_seen_subcommand_from output-volume output-mute input-volume input-mute sinks sources status help" -f -a "status" -d 'Show current audio status'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and not __fish_seen_subcommand_from output-volume output-mute input-volume input-mute sinks sources status help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and __fish_seen_subcommand_from output-volume" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and __fish_seen_subcommand_from output-mute" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and __fish_seen_subcommand_from input-volume" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and __fish_seen_subcommand_from input-mute" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and __fish_seen_subcommand_from sinks" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and __fish_seen_subcommand_from sources" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and __fish_seen_subcommand_from help" -f -a "output-volume" -d 'Get or set output volume level'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and __fish_seen_subcommand_from help" -f -a "output-mute" -d 'Toggle output mute state'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and __fish_seen_subcommand_from help" -f -a "input-volume" -d 'Get or set input volume level'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and __fish_seen_subcommand_from help" -f -a "input-mute" -d 'Toggle input mute state'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and __fish_seen_subcommand_from help" -f -a "sinks" -d 'List available audio sinks (outputs)'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and __fish_seen_subcommand_from help" -f -a "sources" -d 'List available audio sources (inputs)'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and __fish_seen_subcommand_from help" -f -a "status" -d 'Show current audio status'
complete -c wayle -n "__fish_wayle_using_subcommand audio; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wayle -n "__fish_wayle_using_subcommand config; and not __fish_seen_subcommand_from get set reset schema default docs help" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand config; and not __fish_seen_subcommand_from get set reset schema default docs help" -f -a "get" -d 'Get the value of a configuration path'
complete -c wayle -n "__fish_wayle_using_subcommand config; and not __fish_seen_subcommand_from get set reset schema default docs help" -f -a "set" -d 'Set the value of a configuration path'
complete -c wayle -n "__fish_wayle_using_subcommand config; and not __fish_seen_subcommand_from get set reset schema default docs help" -f -a "reset" -d 'Reset a configuration path to its default value'
complete -c wayle -n "__fish_wayle_using_subcommand config; and not __fish_seen_subcommand_from get set reset schema default docs help" -f -a "schema" -d 'Output JSON Schema for the configuration (for editor intellisense)'
complete -c wayle -n "__fish_wayle_using_subcommand config; and not __fish_seen_subcommand_from get set reset schema default docs help" -f -a "default" -d 'Output the default configuration as TOML'
complete -c wayle -n "__fish_wayle_using_subcommand config; and not __fish_seen_subcommand_from get set reset schema default docs help" -f -a "docs" -d 'Generate markdown reference pages for every registered schema'
complete -c wayle -n "__fish_wayle_using_subcommand config; and not __fish_seen_subcommand_from get set reset schema default docs help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wayle -n "__fish_wayle_using_subcommand config; and __fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand config; and __fish_seen_subcommand_from set" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand config; and __fish_seen_subcommand_from reset" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand config; and __fish_seen_subcommand_from schema" -l stdout -d 'Print to stdout instead of writing to config directory'
complete -c wayle -n "__fish_wayle_using_subcommand config; and __fish_seen_subcommand_from schema" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand config; and __fish_seen_subcommand_from default" -l stdout -d 'Print to stdout instead of writing config.toml.example'
complete -c wayle -n "__fish_wayle_using_subcommand config; and __fish_seen_subcommand_from default" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand config; and __fish_seen_subcommand_from docs" -l out -d 'Output directory for the generated pages' -r -F
complete -c wayle -n "__fish_wayle_using_subcommand config; and __fish_seen_subcommand_from docs" -l only -d 'Regenerate only the named module' -r
complete -c wayle -n "__fish_wayle_using_subcommand config; and __fish_seen_subcommand_from docs" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "get" -d 'Get the value of a configuration path'
complete -c wayle -n "__fish_wayle_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "set" -d 'Set the value of a configuration path'
complete -c wayle -n "__fish_wayle_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "reset" -d 'Reset a configuration path to its default value'
complete -c wayle -n "__fish_wayle_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "schema" -d 'Output JSON Schema for the configuration (for editor intellisense)'
complete -c wayle -n "__fish_wayle_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "default" -d 'Output the default configuration as TOML'
complete -c wayle -n "__fish_wayle_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "docs" -d 'Generate markdown reference pages for every registered schema'
complete -c wayle -n "__fish_wayle_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and not __fish_seen_subcommand_from setup install import remove sources list open export help" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and not __fish_seen_subcommand_from setup install import remove sources list open export help" -f -a "setup" -d 'Install bundled icons required by Wayle components'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and not __fish_seen_subcommand_from setup install import remove sources list open export help" -f -a "install" -d 'Install icons from a CDN source'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and not __fish_seen_subcommand_from setup install import remove sources list open export help" -f -a "import" -d 'Import local SVG file(s) as icons'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and not __fish_seen_subcommand_from setup install import remove sources list open export help" -f -a "remove" -d 'Remove installed icons'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and not __fish_seen_subcommand_from setup install import remove sources list open export help" -f -a "sources" -d 'List available icon sources'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and not __fish_seen_subcommand_from setup install import remove sources list open export help" -f -a "list" -d 'List installed icons'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and not __fish_seen_subcommand_from setup install import remove sources list open export help" -f -a "open" -d 'Open the icons directory in file manager'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and not __fish_seen_subcommand_from setup install import remove sources list open export help" -f -a "export" -d 'Export all installed icons to a directory'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and not __fish_seen_subcommand_from setup install import remove sources list open export help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and __fish_seen_subcommand_from setup" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and __fish_seen_subcommand_from install" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and __fish_seen_subcommand_from import" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and __fish_seen_subcommand_from remove" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and __fish_seen_subcommand_from sources" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and __fish_seen_subcommand_from list" -s s -l source -d 'Filter by source prefix (e.g., tb, si, md)' -r
complete -c wayle -n "__fish_wayle_using_subcommand icons; and __fish_seen_subcommand_from list" -s i -l interactive -d 'Interactive fuzzy search (requires fzf)'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and __fish_seen_subcommand_from open" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and __fish_seen_subcommand_from export" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and __fish_seen_subcommand_from help" -f -a "setup" -d 'Install bundled icons required by Wayle components'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and __fish_seen_subcommand_from help" -f -a "install" -d 'Install icons from a CDN source'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and __fish_seen_subcommand_from help" -f -a "import" -d 'Import local SVG file(s) as icons'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and __fish_seen_subcommand_from help" -f -a "remove" -d 'Remove installed icons'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and __fish_seen_subcommand_from help" -f -a "sources" -d 'List available icon sources'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and __fish_seen_subcommand_from help" -f -a "list" -d 'List installed icons'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and __fish_seen_subcommand_from help" -f -a "open" -d 'Open the icons directory in file manager'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and __fish_seen_subcommand_from help" -f -a "export" -d 'Export all installed icons to a directory'
complete -c wayle -n "__fish_wayle_using_subcommand icons; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wayle -n "__fish_wayle_using_subcommand media; and not __fish_seen_subcommand_from list play-pause next previous shuffle loop active info help" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand media; and not __fish_seen_subcommand_from list play-pause next previous shuffle loop active info help" -f -a "list" -d 'List all available media players'
complete -c wayle -n "__fish_wayle_using_subcommand media; and not __fish_seen_subcommand_from list play-pause next previous shuffle loop active info help" -f -a "play-pause" -d 'Toggle play/pause for a media player'
complete -c wayle -n "__fish_wayle_using_subcommand media; and not __fish_seen_subcommand_from list play-pause next previous shuffle loop active info help" -f -a "next" -d 'Skip to next track'
complete -c wayle -n "__fish_wayle_using_subcommand media; and not __fish_seen_subcommand_from list play-pause next previous shuffle loop active info help" -f -a "previous" -d 'Go to previous track'
complete -c wayle -n "__fish_wayle_using_subcommand media; and not __fish_seen_subcommand_from list play-pause next previous shuffle loop active info help" -f -a "shuffle" -d 'Toggle or set shuffle mode'
complete -c wayle -n "__fish_wayle_using_subcommand media; and not __fish_seen_subcommand_from list play-pause next previous shuffle loop active info help" -f -a "loop" -d 'Set loop/repeat mode'
complete -c wayle -n "__fish_wayle_using_subcommand media; and not __fish_seen_subcommand_from list play-pause next previous shuffle loop active info help" -f -a "active" -d 'Get or set the active media player'
complete -c wayle -n "__fish_wayle_using_subcommand media; and not __fish_seen_subcommand_from list play-pause next previous shuffle loop active info help" -f -a "info" -d 'Display detailed information about a media player'
complete -c wayle -n "__fish_wayle_using_subcommand media; and not __fish_seen_subcommand_from list play-pause next previous shuffle loop active info help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wayle -n "__fish_wayle_using_subcommand media; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand media; and __fish_seen_subcommand_from play-pause" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand media; and __fish_seen_subcommand_from next" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand media; and __fish_seen_subcommand_from previous" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand media; and __fish_seen_subcommand_from shuffle" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c wayle -n "__fish_wayle_using_subcommand media; and __fish_seen_subcommand_from loop" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c wayle -n "__fish_wayle_using_subcommand media; and __fish_seen_subcommand_from active" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand media; and __fish_seen_subcommand_from info" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand media; and __fish_seen_subcommand_from help" -f -a "list" -d 'List all available media players'
complete -c wayle -n "__fish_wayle_using_subcommand media; and __fish_seen_subcommand_from help" -f -a "play-pause" -d 'Toggle play/pause for a media player'
complete -c wayle -n "__fish_wayle_using_subcommand media; and __fish_seen_subcommand_from help" -f -a "next" -d 'Skip to next track'
complete -c wayle -n "__fish_wayle_using_subcommand media; and __fish_seen_subcommand_from help" -f -a "previous" -d 'Go to previous track'
complete -c wayle -n "__fish_wayle_using_subcommand media; and __fish_seen_subcommand_from help" -f -a "shuffle" -d 'Toggle or set shuffle mode'
complete -c wayle -n "__fish_wayle_using_subcommand media; and __fish_seen_subcommand_from help" -f -a "loop" -d 'Set loop/repeat mode'
complete -c wayle -n "__fish_wayle_using_subcommand media; and __fish_seen_subcommand_from help" -f -a "active" -d 'Get or set the active media player'
complete -c wayle -n "__fish_wayle_using_subcommand media; and __fish_seen_subcommand_from help" -f -a "info" -d 'Display detailed information about a media player'
complete -c wayle -n "__fish_wayle_using_subcommand media; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wayle -n "__fish_wayle_using_subcommand notify; and not __fish_seen_subcommand_from list dismiss dismiss-all dnd status help" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand notify; and not __fish_seen_subcommand_from list dismiss dismiss-all dnd status help" -f -a "list" -d 'List all notifications'
complete -c wayle -n "__fish_wayle_using_subcommand notify; and not __fish_seen_subcommand_from list dismiss dismiss-all dnd status help" -f -a "dismiss" -d 'Dismiss a notification by ID'
complete -c wayle -n "__fish_wayle_using_subcommand notify; and not __fish_seen_subcommand_from list dismiss dismiss-all dnd status help" -f -a "dismiss-all" -d 'Dismiss all notifications'
complete -c wayle -n "__fish_wayle_using_subcommand notify; and not __fish_seen_subcommand_from list dismiss dismiss-all dnd status help" -f -a "dnd" -d 'Toggle Do Not Disturb mode'
complete -c wayle -n "__fish_wayle_using_subcommand notify; and not __fish_seen_subcommand_from list dismiss dismiss-all dnd status help" -f -a "status" -d 'Show notification status'
complete -c wayle -n "__fish_wayle_using_subcommand notify; and not __fish_seen_subcommand_from list dismiss dismiss-all dnd status help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wayle -n "__fish_wayle_using_subcommand notify; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand notify; and __fish_seen_subcommand_from dismiss" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand notify; and __fish_seen_subcommand_from dismiss-all" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand notify; and __fish_seen_subcommand_from dnd" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand notify; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand notify; and __fish_seen_subcommand_from help" -f -a "list" -d 'List all notifications'
complete -c wayle -n "__fish_wayle_using_subcommand notify; and __fish_seen_subcommand_from help" -f -a "dismiss" -d 'Dismiss a notification by ID'
complete -c wayle -n "__fish_wayle_using_subcommand notify; and __fish_seen_subcommand_from help" -f -a "dismiss-all" -d 'Dismiss all notifications'
complete -c wayle -n "__fish_wayle_using_subcommand notify; and __fish_seen_subcommand_from help" -f -a "dnd" -d 'Toggle Do Not Disturb mode'
complete -c wayle -n "__fish_wayle_using_subcommand notify; and __fish_seen_subcommand_from help" -f -a "status" -d 'Show notification status'
complete -c wayle -n "__fish_wayle_using_subcommand notify; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and not __fish_seen_subcommand_from start stop restart status settings inspect hide show toggle help" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and not __fish_seen_subcommand_from start stop restart status settings inspect hide show toggle help" -f -a "start" -d 'Start the panel daemon'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and not __fish_seen_subcommand_from start stop restart status settings inspect hide show toggle help" -f -a "stop" -d 'Stop the panel daemon'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and not __fish_seen_subcommand_from start stop restart status settings inspect hide show toggle help" -f -a "restart" -d 'Restart the panel daemon'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and not __fish_seen_subcommand_from start stop restart status settings inspect hide show toggle help" -f -a "status" -d 'Check panel status'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and not __fish_seen_subcommand_from start stop restart status settings inspect hide show toggle help" -f -a "settings" -d 'Open panel settings'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and not __fish_seen_subcommand_from start stop restart status settings inspect hide show toggle help" -f -a "inspect" -d 'Open GTK Inspector for debugging'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and not __fish_seen_subcommand_from start stop restart status settings inspect hide show toggle help" -f -a "hide" -d 'Hide the bar on a monitor'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and not __fish_seen_subcommand_from start stop restart status settings inspect hide show toggle help" -f -a "show" -d 'Show the bar on a monitor'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and not __fish_seen_subcommand_from start stop restart status settings inspect hide show toggle help" -f -a "toggle" -d 'Toggle bar visibility on a monitor'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and not __fish_seen_subcommand_from start stop restart status settings inspect hide show toggle help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and __fish_seen_subcommand_from start" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and __fish_seen_subcommand_from stop" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and __fish_seen_subcommand_from restart" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and __fish_seen_subcommand_from settings" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and __fish_seen_subcommand_from inspect" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and __fish_seen_subcommand_from hide" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and __fish_seen_subcommand_from show" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and __fish_seen_subcommand_from toggle" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and __fish_seen_subcommand_from help" -f -a "start" -d 'Start the panel daemon'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and __fish_seen_subcommand_from help" -f -a "stop" -d 'Stop the panel daemon'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and __fish_seen_subcommand_from help" -f -a "restart" -d 'Restart the panel daemon'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and __fish_seen_subcommand_from help" -f -a "status" -d 'Check panel status'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and __fish_seen_subcommand_from help" -f -a "settings" -d 'Open panel settings'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and __fish_seen_subcommand_from help" -f -a "inspect" -d 'Open GTK Inspector for debugging'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and __fish_seen_subcommand_from help" -f -a "hide" -d 'Hide the bar on a monitor'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and __fish_seen_subcommand_from help" -f -a "show" -d 'Show the bar on a monitor'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and __fish_seen_subcommand_from help" -f -a "toggle" -d 'Toggle bar visibility on a monitor'
complete -c wayle -n "__fish_wayle_using_subcommand panel; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wayle -n "__fish_wayle_using_subcommand power; and not __fish_seen_subcommand_from status set cycle list help" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand power; and not __fish_seen_subcommand_from status set cycle list help" -f -a "status" -d 'Show current power profile'
complete -c wayle -n "__fish_wayle_using_subcommand power; and not __fish_seen_subcommand_from status set cycle list help" -f -a "set" -d 'Set power profile'
complete -c wayle -n "__fish_wayle_using_subcommand power; and not __fish_seen_subcommand_from status set cycle list help" -f -a "cycle" -d 'Cycle to next power profile'
complete -c wayle -n "__fish_wayle_using_subcommand power; and not __fish_seen_subcommand_from status set cycle list help" -f -a "list" -d 'List available power profiles'
complete -c wayle -n "__fish_wayle_using_subcommand power; and not __fish_seen_subcommand_from status set cycle list help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wayle -n "__fish_wayle_using_subcommand power; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand power; and __fish_seen_subcommand_from set" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand power; and __fish_seen_subcommand_from cycle" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand power; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand power; and __fish_seen_subcommand_from help" -f -a "status" -d 'Show current power profile'
complete -c wayle -n "__fish_wayle_using_subcommand power; and __fish_seen_subcommand_from help" -f -a "set" -d 'Set power profile'
complete -c wayle -n "__fish_wayle_using_subcommand power; and __fish_seen_subcommand_from help" -f -a "cycle" -d 'Cycle to next power profile'
complete -c wayle -n "__fish_wayle_using_subcommand power; and __fish_seen_subcommand_from help" -f -a "list" -d 'List available power profiles'
complete -c wayle -n "__fish_wayle_using_subcommand power; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wayle -n "__fish_wayle_using_subcommand systray; and not __fish_seen_subcommand_from list activate status help" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand systray; and not __fish_seen_subcommand_from list activate status help" -f -a "list" -d 'List all system tray items'
complete -c wayle -n "__fish_wayle_using_subcommand systray; and not __fish_seen_subcommand_from list activate status help" -f -a "activate" -d 'Activate a tray item by ID'
complete -c wayle -n "__fish_wayle_using_subcommand systray; and not __fish_seen_subcommand_from list activate status help" -f -a "status" -d 'Show system tray status'
complete -c wayle -n "__fish_wayle_using_subcommand systray; and not __fish_seen_subcommand_from list activate status help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wayle -n "__fish_wayle_using_subcommand systray; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand systray; and __fish_seen_subcommand_from activate" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand systray; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand systray; and __fish_seen_subcommand_from help" -f -a "list" -d 'List all system tray items'
complete -c wayle -n "__fish_wayle_using_subcommand systray; and __fish_seen_subcommand_from help" -f -a "activate" -d 'Activate a tray item by ID'
complete -c wayle -n "__fish_wayle_using_subcommand systray; and __fish_seen_subcommand_from help" -f -a "status" -d 'Show system tray status'
complete -c wayle -n "__fish_wayle_using_subcommand systray; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and not __fish_seen_subcommand_from set cycle stop next previous info theming-monitor help" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and not __fish_seen_subcommand_from set cycle stop next previous info theming-monitor help" -f -a "set" -d 'Set wallpaper from an image file'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and not __fish_seen_subcommand_from set cycle stop next previous info theming-monitor help" -f -a "cycle" -d 'Start cycling wallpapers from a directory'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and not __fish_seen_subcommand_from set cycle stop next previous info theming-monitor help" -f -a "stop" -d 'Stop wallpaper cycling'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and not __fish_seen_subcommand_from set cycle stop next previous info theming-monitor help" -f -a "next" -d 'Skip to next wallpaper'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and not __fish_seen_subcommand_from set cycle stop next previous info theming-monitor help" -f -a "previous" -d 'Go back to previous wallpaper'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and not __fish_seen_subcommand_from set cycle stop next previous info theming-monitor help" -f -a "info" -d 'Display current wallpaper information'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and not __fish_seen_subcommand_from set cycle stop next previous info theming-monitor help" -f -a "theming-monitor" -d 'Set which monitor to use for color extraction'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and not __fish_seen_subcommand_from set cycle stop next previous info theming-monitor help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and __fish_seen_subcommand_from set" -s f -l fit -d 'Image fit mode' -r -f -a "fill\t'Scale to cover entire display'
fit\t'Scale to fit within display'
center\t'Display at original size, centered'
tile\t'Tile the image'
stretch\t'Stretch to fill'"
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and __fish_seen_subcommand_from set" -l monitor -d 'Target monitor (e.g., DP-1, HDMI-A-1). If omitted, applies to all monitors' -r
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and __fish_seen_subcommand_from set" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and __fish_seen_subcommand_from cycle" -s i -l interval -d 'Interval in seconds between changes' -r
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and __fish_seen_subcommand_from cycle" -s m -l mode -d 'Cycling mode' -r -f -a "sequential\t'Cycle in alphabetical order'
shuffle\t'Cycle in random order'"
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and __fish_seen_subcommand_from cycle" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and __fish_seen_subcommand_from stop" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and __fish_seen_subcommand_from next" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and __fish_seen_subcommand_from previous" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and __fish_seen_subcommand_from info" -l monitor -d 'Target monitor (e.g., DP-1, HDMI-A-1). If omitted, shows global state' -r
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and __fish_seen_subcommand_from info" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and __fish_seen_subcommand_from theming-monitor" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and __fish_seen_subcommand_from help" -f -a "set" -d 'Set wallpaper from an image file'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and __fish_seen_subcommand_from help" -f -a "cycle" -d 'Start cycling wallpapers from a directory'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and __fish_seen_subcommand_from help" -f -a "stop" -d 'Stop wallpaper cycling'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and __fish_seen_subcommand_from help" -f -a "next" -d 'Skip to next wallpaper'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and __fish_seen_subcommand_from help" -f -a "previous" -d 'Go back to previous wallpaper'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and __fish_seen_subcommand_from help" -f -a "info" -d 'Display current wallpaper information'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and __fish_seen_subcommand_from help" -f -a "theming-monitor" -d 'Set which monitor to use for color extraction'
complete -c wayle -n "__fish_wayle_using_subcommand wallpaper; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and not __fish_seen_subcommand_from on off duration remaining status toggle help" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and not __fish_seen_subcommand_from on off duration remaining status toggle help" -f -a "on" -d 'Enable idle inhibition'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and not __fish_seen_subcommand_from on off duration remaining status toggle help" -f -a "off" -d 'Disable idle inhibition'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and not __fish_seen_subcommand_from on off duration remaining status toggle help" -f -a "duration" -d 'Adjust timer duration (upper limit)'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and not __fish_seen_subcommand_from on off duration remaining status toggle help" -f -a "remaining" -d 'Adjust remaining time on active timer'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and not __fish_seen_subcommand_from on off duration remaining status toggle help" -f -a "status" -d 'Show current idle inhibit status'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and not __fish_seen_subcommand_from on off duration remaining status toggle help" -f -a "toggle" -d 'Toggle idle inhibition on/off'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and not __fish_seen_subcommand_from on off duration remaining status toggle help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and __fish_seen_subcommand_from on" -s i -l indefinite -d 'Force indefinite mode (ignore default duration)'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and __fish_seen_subcommand_from on" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and __fish_seen_subcommand_from off" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and __fish_seen_subcommand_from duration" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and __fish_seen_subcommand_from remaining" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and __fish_seen_subcommand_from toggle" -s i -l indefinite -d 'Use indefinite mode when enabling'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and __fish_seen_subcommand_from toggle" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and __fish_seen_subcommand_from help" -f -a "on" -d 'Enable idle inhibition'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and __fish_seen_subcommand_from help" -f -a "off" -d 'Disable idle inhibition'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and __fish_seen_subcommand_from help" -f -a "duration" -d 'Adjust timer duration (upper limit)'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and __fish_seen_subcommand_from help" -f -a "remaining" -d 'Adjust remaining time on active timer'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and __fish_seen_subcommand_from help" -f -a "status" -d 'Show current idle inhibit status'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and __fish_seen_subcommand_from help" -f -a "toggle" -d 'Toggle idle inhibition on/off'
complete -c wayle -n "__fish_wayle_using_subcommand idle; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wayle -n "__fish_wayle_using_subcommand shell" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand completions" -s h -l help -d 'Print help'
complete -c wayle -n "__fish_wayle_using_subcommand help; and not __fish_seen_subcommand_from audio config icons media notify panel power systray wallpaper idle shell completions help" -f -a "audio" -d 'Audio control commands'
complete -c wayle -n "__fish_wayle_using_subcommand help; and not __fish_seen_subcommand_from audio config icons media notify panel power systray wallpaper idle shell completions help" -f -a "config" -d 'Configuration management commands'
complete -c wayle -n "__fish_wayle_using_subcommand help; and not __fish_seen_subcommand_from audio config icons media notify panel power systray wallpaper idle shell completions help" -f -a "icons" -d 'Icon management commands'
complete -c wayle -n "__fish_wayle_using_subcommand help; and not __fish_seen_subcommand_from audio config icons media notify panel power systray wallpaper idle shell completions help" -f -a "media" -d 'Media player control commands'
complete -c wayle -n "__fish_wayle_using_subcommand help; and not __fish_seen_subcommand_from audio config icons media notify panel power systray wallpaper idle shell completions help" -f -a "notify" -d 'Notification control commands'
complete -c wayle -n "__fish_wayle_using_subcommand help; and not __fish_seen_subcommand_from audio config icons media notify panel power systray wallpaper idle shell completions help" -f -a "panel" -d 'Panel management commands'
complete -c wayle -n "__fish_wayle_using_subcommand help; and not __fish_seen_subcommand_from audio config icons media notify panel power systray wallpaper idle shell completions help" -f -a "power" -d 'Power profile commands'
complete -c wayle -n "__fish_wayle_using_subcommand help; and not __fish_seen_subcommand_from audio config icons media notify panel power systray wallpaper idle shell completions help" -f -a "systray" -d 'System tray commands'
complete -c wayle -n "__fish_wayle_using_subcommand help; and not __fish_seen_subcommand_from audio config icons media notify panel power systray wallpaper idle shell completions help" -f -a "wallpaper" -d 'Wallpaper control commands'
complete -c wayle -n "__fish_wayle_using_subcommand help; and not __fish_seen_subcommand_from audio config icons media notify panel power systray wallpaper idle shell completions help" -f -a "idle" -d 'Idle inhibit control commands'
complete -c wayle -n "__fish_wayle_using_subcommand help; and not __fish_seen_subcommand_from audio config icons media notify panel power systray wallpaper idle shell completions help" -f -a "shell" -d 'Run the desktop shell in the foreground'
complete -c wayle -n "__fish_wayle_using_subcommand help; and not __fish_seen_subcommand_from audio config icons media notify panel power systray wallpaper idle shell completions help" -f -a "completions" -d 'Generate shell completions'
complete -c wayle -n "__fish_wayle_using_subcommand help; and not __fish_seen_subcommand_from audio config icons media notify panel power systray wallpaper idle shell completions help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from audio" -f -a "output-volume" -d 'Get or set output volume level'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from audio" -f -a "output-mute" -d 'Toggle output mute state'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from audio" -f -a "input-volume" -d 'Get or set input volume level'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from audio" -f -a "input-mute" -d 'Toggle input mute state'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from audio" -f -a "sinks" -d 'List available audio sinks (outputs)'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from audio" -f -a "sources" -d 'List available audio sources (inputs)'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from audio" -f -a "status" -d 'Show current audio status'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from config" -f -a "get" -d 'Get the value of a configuration path'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from config" -f -a "set" -d 'Set the value of a configuration path'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from config" -f -a "reset" -d 'Reset a configuration path to its default value'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from config" -f -a "schema" -d 'Output JSON Schema for the configuration (for editor intellisense)'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from config" -f -a "default" -d 'Output the default configuration as TOML'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from config" -f -a "docs" -d 'Generate markdown reference pages for every registered schema'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from icons" -f -a "setup" -d 'Install bundled icons required by Wayle components'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from icons" -f -a "install" -d 'Install icons from a CDN source'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from icons" -f -a "import" -d 'Import local SVG file(s) as icons'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from icons" -f -a "remove" -d 'Remove installed icons'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from icons" -f -a "sources" -d 'List available icon sources'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from icons" -f -a "list" -d 'List installed icons'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from icons" -f -a "open" -d 'Open the icons directory in file manager'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from icons" -f -a "export" -d 'Export all installed icons to a directory'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from media" -f -a "list" -d 'List all available media players'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from media" -f -a "play-pause" -d 'Toggle play/pause for a media player'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from media" -f -a "next" -d 'Skip to next track'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from media" -f -a "previous" -d 'Go to previous track'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from media" -f -a "shuffle" -d 'Toggle or set shuffle mode'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from media" -f -a "loop" -d 'Set loop/repeat mode'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from media" -f -a "active" -d 'Get or set the active media player'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from media" -f -a "info" -d 'Display detailed information about a media player'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from notify" -f -a "list" -d 'List all notifications'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from notify" -f -a "dismiss" -d 'Dismiss a notification by ID'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from notify" -f -a "dismiss-all" -d 'Dismiss all notifications'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from notify" -f -a "dnd" -d 'Toggle Do Not Disturb mode'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from notify" -f -a "status" -d 'Show notification status'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from panel" -f -a "start" -d 'Start the panel daemon'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from panel" -f -a "stop" -d 'Stop the panel daemon'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from panel" -f -a "restart" -d 'Restart the panel daemon'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from panel" -f -a "status" -d 'Check panel status'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from panel" -f -a "settings" -d 'Open panel settings'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from panel" -f -a "inspect" -d 'Open GTK Inspector for debugging'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from panel" -f -a "hide" -d 'Hide the bar on a monitor'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from panel" -f -a "show" -d 'Show the bar on a monitor'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from panel" -f -a "toggle" -d 'Toggle bar visibility on a monitor'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from power" -f -a "status" -d 'Show current power profile'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from power" -f -a "set" -d 'Set power profile'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from power" -f -a "cycle" -d 'Cycle to next power profile'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from power" -f -a "list" -d 'List available power profiles'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from systray" -f -a "list" -d 'List all system tray items'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from systray" -f -a "activate" -d 'Activate a tray item by ID'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from systray" -f -a "status" -d 'Show system tray status'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from wallpaper" -f -a "set" -d 'Set wallpaper from an image file'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from wallpaper" -f -a "cycle" -d 'Start cycling wallpapers from a directory'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from wallpaper" -f -a "stop" -d 'Stop wallpaper cycling'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from wallpaper" -f -a "next" -d 'Skip to next wallpaper'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from wallpaper" -f -a "previous" -d 'Go back to previous wallpaper'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from wallpaper" -f -a "info" -d 'Display current wallpaper information'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from wallpaper" -f -a "theming-monitor" -d 'Set which monitor to use for color extraction'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from idle" -f -a "on" -d 'Enable idle inhibition'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from idle" -f -a "off" -d 'Disable idle inhibition'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from idle" -f -a "duration" -d 'Adjust timer duration (upper limit)'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from idle" -f -a "remaining" -d 'Adjust remaining time on active timer'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from idle" -f -a "status" -d 'Show current idle inhibit status'
complete -c wayle -n "__fish_wayle_using_subcommand help; and __fish_seen_subcommand_from idle" -f -a "toggle" -d 'Toggle idle inhibition on/off'
